### ISSUE TITLE
The perfectly overlapping boxes are not visible in drawing area

### ISSUE THREAD

**Issue by lrob** [opencv/cvat#1067]
We load automatically generated annotations. In this case it happens that perfectly overlapping boxes are generated (exactly the same coordinates with different class). While reviewing the annotation using cvat it is very difficult to note that this has happened and often the person reviewing the annotations does not remove the extra annotations.

It would be nice to have an alert when a perfect overlapping is present on a frame or to have a bi-color box depicting overlapping boxes.

**Comment by bsekachev** [comment]
@lrob 

Hi, in the PR #1067 we have added a slider to switch z layers. 
Slider is enabled if several z layers are on a frame (shapes with different ``zOrder`` value). It is something like an alert you mentioned. 
By sliding it to the highest value you can see how shapes are being added to canvas incrementally. 
Providing different ``zOrder`` values for overlapped shapes is your own business (I suppose it is not a big deal). 

What do you think?

**Comment by lrob** [comment]
It is not very clear where the slider appears. Is it a propery of the frame
and is it present also in the case of partially overlapping boxes. If that
the case it would not work as an alert for perfect overlapping boxed
because partial overlap is presresent almost in all the frames.

**Comment by bsekachev** [comment]
@lrob 

> It is not very clear where the slider appears.

Slider position is fixed and it is displayed always, or I don't undestand the problem.

Do not consider the feature like ``indicator of overlapping``. Actually it is slider to switching a layer (imagine that there are a lot of layers of annotations on the image [baground, middle, foreground, etc.]). It doesn't matter if there are full or partial overlapping because it works based on ``zOrder`` value of an object (literally it is just a number of a layer) which is specified by a user.

**Comment by bsekachev** [comment]
So, no comments any more here. I suppose we can close the issue. Do not hesitate reopen it if you still need help
