### ISSUE TITLE
Keypoint Annotation

### ISSUE THREAD

**Issue by aaelsay2** [opencv/cvat#12]
I wanted to ask about the keypoint annotation feature you are workig on now. Would that have standard configuration/format like keypoints for annotating human pose? Would it have the same interpolation feature as the current bounding boxes? Finally when would the feature be released? Do you have specific date in mind? Thank you

**Comment by bsekachev** [comment]
Hello, thanks for you question!
* Now we are developing and debugging this feature. You will can choose the shape "points" instead of "bbox" (also "polygon" and "polyline" will be supported) and create point array by clicks on an image. Array will support the fixed order of points. It also may contain only one point. One label will correspond to one array (as in bbox case). Of course, you will can edit (drag and resize) all new shapes. 
* Points, polygons and polylines will not support the interpolation between frames, but you will can merge it to one track.
* It will be released in end of September, I suppose, if problems will not occur.

**Comment by nmanovic** [comment]
Done in `develop` branch. Documentation will be updated lately.

**Comment by moiseevigor** [comment]
@nmanovic Sorry for commenting on the closed issue, but cannot find any reference for the implementation of keypoints annotation in CVAT. As I understood the points is an answer, but do you have any plans to make it compatible with a COCO format for keypoint names and "skeleton"?

**Comment by nmanovic** [comment]
Hi @moiseevigor ,

Could you please submit a separate issue about features which you want to have in CVAT regarding keypoints? We want to support COCO format in the nearest feature. I'm not sure about skeleton yet because we don't have many such tasks internally yet. If you can help to describe features which you want to get or even send us a PR it will be helpful.

**Comment by aalzooke** [comment]
Does CVAT support keypoint for coco format? Thanks

**Comment by nmanovic** [comment]
@zhiltsov-max , could you please cover the question?
