### ISSUE TITLE
Image freezes when try moving points

### ISSUE THREAD

**Issue by elentrika** [opencv/cvat#1223]
Whenever I try to move the point the image freezes.. In the image the point becomes inactive after moving the point. Is this the cvat version issue.. If yes how to downgrade the version. I could do this properly in the previous version.
![Screenshot from 2020-03-02 14-48-00](https://user-images.githubusercontent.com/61613134/75662361-f3989600-5c94-11ea-885b-67cead09ba77.png)

**Comment by bsekachev** [comment]
@elentrika 

We have recently fix similar bug. 
Try to update CVAT.

**Comment by elentrika** [comment]
> @elentrika
> 
> We have recently fix similar bug.
> Try to update CVAT.

tried to upgrade by following the steps given by you but it give me network authentication error

**Comment by bsekachev** [comment]
@elentrika 

Do you use default ``docker-compose`` file?
If you don't, be sure that you setup it right, because the way of configuration has been [changed](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#advanced-settings).
Also please clear the browser cache.
If it doesn't help, send us exact error from the browser console.

**Comment by bsekachev** [comment]
@elentrika 

Are you still experiencing the issue or it can be closed?

**Comment by bsekachev** [comment]
Let's close the issue for now. Do not hesitate reopen it if you are still experiencing it.
