### ISSUE TITLE
Upgrade to release 0.2

### ISSUE THREAD

**Issue by headdab** [opencv/cvat#124]
In issue #14, there was a discussion about whether removal of the data volumes was to be done when doing 'docker down'.  As far as I can tell, the decision was to not remove the data volume.  Is that correct?

Furthermore, it doesn't look like there haven't been any backward incompatible changes to the export format.  Are there any issues that I need to be aware of when upgrading to 0.2 from 0.1?

Can I essentially do:
- docker down
- update master branch to 0.2
- docker up
?

If not, can I download my tag XML from 0.1, update the running instance, and then upload the tag XML?

Thanks.

**Comment by robgf** [comment]
Not sure if this answers your question but I have done the equivalent to your steps.  The volumes are preserved when you 'docker down' you can change to any other branch, I have hen rebuilt  image since bring down the image was to tweak it and then used 'docker up' and everything you'd expect from the volume still works accounts, tasks...

**Comment by nmanovic** [comment]
Hi @headdab ,

I cannot guarantee that it is safe but internally we did the same. The tool is built on Django and relies on "migration" from the framework. Please backup your database before such manipulations to be able to restore in case of any problems.

Does it answer your question?

**Comment by headdab** [comment]
Yes.  Thanks for the responses.
I backed it up, but everything seems to be fine with a restore.
