### ISSUE TITLE
How to build CVAT with OpenVINO on windows host?

### ISSUE THREAD

**Issue by MannAgrawal** [opencv/cvat#1397]
I'm trying to set up semi-automatic segmentation for window 

https://github.com/opencv/cvat/blob/master/cvat/apps/dextr_segmentation/README.md
But every time I finish drawing a polygon after setting extreme point, I am getting this error
Segmentation has fallen. Error: 'RuntimeError: Cannot load library '/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so': /opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so: cannot open shared object file: No such file or directory '
but its that a Linux location  so how to build Cvat with openvino in windows???

**Comment by bsekachev** [comment]
@MannAgrawal 

Production CVAT works inside docker container (think about it like if it was a virtual machine with Ubuntu 16.04). 
It is a reason why you see linux path, because CVAT works from linux. 
To setup OpenVINO in docker container follow the [installation guide](https://github.com/opencv/cvat/tree/master/components/openvino).

Use both docker compose options for build: ``-f components/openvino/docker-compose.openvino.yml -f cvat/apps/dextr_segmentation/docker-compose.dextr.yml build`` as it specified [here](https://github.com/opencv/cvat/blob/master/cvat/apps/dextr_segmentation/README.md)

You **DO NOT NEED** to install OpenVINO on host operating system (windows in your case).

**Comment by azhavoro** [comment]
Hi, you should update CVAT or use openvino v2019.x
opencv/cvat#1269 adds support of openvino 2020

**Comment by MannAgrawal** [comment]
@azhavoro hi, Yes I did that and it worked, thank you so much for this.
