### ISSUE TITLE
not able to loggin with swagger created client

### ISSUE THREAD

**Issue by verasativa** [opencv/cvat#1517]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)
- [x ] Asked in gitter channel

```bash
swagger-codegen-cli generate -i mycvatswagger.json -l python -o ../swagger_client
```
### Expected Behaviour

I should be able to connect as described on client documentation (generated from swagger.json)
like:
```python
# Configure HTTP basic authorization: Basic
configuration = swagger_client.Configuration()
configuration.username = 'admin'
configuration.password = 'secretpassword'
configuration.debug = True

try:
    # Returns a paginated list of tasks according to query parameters (10 tasks per page)
    api_response = api_instance.api_v1_tasks_list()
    pprint(api_response)
except ApiException as e:
    print("Exception when calling ApiApi->api_v1_tasks_list: %s\n" % e)
```
### Current Behaviour

It fails with a:
```
HTTP response body: {"detail":"Invalid username/password."}
```
### Steps to Reproduce (for bugs)

1. download you swagger.json
2. generate you swagger_client (as described before)
3. try to list you're task with valid credentials (with client documentation code)

### Your Environment

- Git hash commit (`git log -1`):
1.0.0 release
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
no
- Operating System and version (e.g. Linux, Windows, MacOS):
client on macos, server ubuntu
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.
Also asked here.

**Comment by nmanovic** [comment]
@verasativa , thanks for the bug report. Could you please help us to fix it?

**Comment by gdj0nes** [comment]
I've built my python client for working with cvat around a swagger codegen base. There are a few inconsistencies that should be addressed between the API as it is documented and its true interface. 

Using the auth token as the default rather than username and password is a simple change to the settings.py  However the response field for a 200 response to the login field to return a key is undocumented. 

Another bug is in the spec for files, (client, server, remote). The current spec says that filenames are placed under a file key when it actually accepts a list of strings. I think it would be good to change the cvat client to nest filenames names under the file key as it is documented. In the future this could allow for extending the file model more easily to include additional specifications, e.g. content type into the data model.

**Comment by nmanovic** [comment]
@gdj0nes , I agree. Could you please help us to fix that?

**Comment by gdj0nes** [comment]
@nmanovic is it better in your mind to update the front end to meed the document interface or change the documentation of the interface.
