### ISSUE TITLE
 '404 Not Found' error when running docker Analytics 

### ISSUE THREAD

**Issue by zardadi** [opencv/cvat#1527]
To create the issue:
1- Install CVAT 
2- Add docker-compose.override.yml file to add server info and shared path link 
3- Run 'docker-compose up -d' to run CVAT on server 
4- Run 'docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml build' to build docker image
4- Run 'docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml up -d' to run docker container

Server version is 0.6.1
Core, Canvas, UI versions 0.5.2

If we run steps 1 to 3, CVAT works fine on the server. 
If we skip step 2, CVAT works fine on the local host and Analytics tap works fine as well. 
But when we try to have Analytics on server, we see the issue.

**Comment by azhavoro** [comment]
@zardadi Hi,
When you specify config file(s) with `-f` you should include `docker-compose.override.yml` file to the 4'th and 5'th commands as well, because docker-compose doesn't read the override file in this case:
`docker-compose -f docker-compose.yml -f docker-compose.override.yml -f components/analytics/docker-compose.analytics.yml build`
`docker-compose -f docker-compose.yml -f docker-compose.override.yml -f components/analytics/docker-compose.analytics.yml up -d`
I'll close the issue, feel free to re-open if this issue still actual for you.
