### ISSUE TITLE
Wrong API Documentation for /tasks/{id}/data in Swagger

### ISSUE THREAD

**Issue by dev225reddys** [opencv/cvat#1543]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

- Swagger Documentation for [POST] "/tasks/{id}/data", should show:
`{
  "client_files": [
    {}
  ],
  "server_files": [
    {
      "file": "string"
    }
  ],
  "remote_files": [
    {
      "file": "string"
    }
  ]
}`

### Current Behaviour

- Swagger Documentation is showing "/tasks[POST]" Request JSON for "/tasks/{id}/data" which is wrong.
- It is showing following :
`{
  "name": "string",
  "owner": 0,
  "assignee": 0,
  "bug_tracker": "string",
  "overlap": 0,
  "segment_size": 0,
  "z_order": true,
  "labels": [
    {
      "name": "string",
      "attributes": [
        {
          "name": "string",
          "mutable": true,
          "input_type": "checkbox",
          "default_value": "string",
          "values": "string"
        }
      ]
    }
  ],
  "project": 0
}`
![localhost_8080_api_swagger_](https://user-images.githubusercontent.com/22456094/82008140-85efe980-9689-11ea-9fa7-68641042d694.png)

### Possible Solution

- Update Swagger Documentation for /tasks/{id}/data

### Git Branch
- Facing this issue in "develop" Branch with Latest Commit.

**Comment by nmanovic** [comment]
@dev225reddys , thanks for reporting the issue. Do you think you can help us with the issue?

**Comment by kaustubhharapanahalli** [comment]
@nmanovic Today, even I was facing some issue with the same REST call. 
In the earlier versions of the Swagger API, we didn't have to send the image_quality as a parameter, but in current version, it is requesting for the image_quality as a parameter.

To give a brief on how the cURL command looked earlier: 

1. Creating a task
```
curl --location --request POST 'http://localhost:8080/api/v1/tasks' --header 'Content-Type: application/json' --data-raw '{"name":"test","labels":[{"name":"person","attributes":[]}],"image_quality":50,"z_order":false,"bug_tracker":""}' -u "admin":"admin"
```

2. Loading the data
curl --location --request POST 'http://localhost:8080/api/v1/tasks/4/data' --header 'Content-Type: multipart/form-data' --form 'server_files[0]=sample_pedestrian_dataset' -u "admin":"admin"

But now, after we create the task using the command mentioned in (1), if we want to load data to a particular task, it throws an error asking for image_quality as a parameter.

Is it due to some URL changes in loading the data?

**Comment by nmanovic** [comment]
@azhavoro , can we make the parameter by default? Could you please look?

**Comment by kaustubhharapanahalli** [comment]
@nmanovic: @azhavoro gave me a command and it works. The command is: 

```
curl --location --request POST 'http://localhost:8080/api/v1/tasks/32/data' --header 'Content-Type: multipart/form-data' --form 'server_files[0]=1.jpg' --form 'image_quality=100' --form 'use_zip_chunks=true'  -u "admin":"admin"
```
 
In the documentation, the changes that are needed to be done are marking things as **is required** which is missing.
