### ISSUE TITLE
Paint Brush like to tool to fix the auto-annotated segmentation regions

### ISSUE THREAD

**Issue by kaustubhharapanahalli** [opencv/cvat#1849]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
A paint brush like tool for selecting segmentation region to correct automatic annotations. 

### Current Behaviour
The annotation points have to be moved around to fix the generated annotations.

### Context
The segmentation annotations that were generated, have points. If I need to fix the generated annotations, I will have to move the points around to fit the expected annotation region. Since a generated polygon has multiple points, it's hard to manage them. Having a paint brush like feature will help in fixing the segmentation annotations easy.

**Comment by Optimox** [comment]
A paint brush would be very helpful!

**Comment by MarioProjects** [comment]
The software is amazing!! A brush could speed up the segmentation in a lot of problems, waiting for it! Thanks again

**Comment by nmanovic** [comment]
@nstolyarov , could you please confirm that the feature can improve data annotation experience for your tasks?

**Comment by DbrRoxane** [comment]
Hi @nmanovic , I do not think tha the hole cutting in polygons helps much for this. It is useful but quite different need. 
In other tools, one can refine (extend or erase) polygone's borders thanks to a brush and this is extremely practical. 
In my case, I use the automaic annotation with HRNET (which is great, bw) but not precise enough. 
A brush with several difference width such as the ones we can find on GIMP, paint, etc.


![grafik](https://user-images.githubusercontent.com/32749371/147081738-eb45197c-0875-4acf-be10-3ee3f6581b72.png)

For instance, here, I wish I could simply easily extend the green area without having to move one point per one.  In addition to be long it is ususally not possible at al to change the shape of the pre-annoated items because we have to respect the exact amount of points during the editing.

**Comment by osvadimos** [comment]
Brush would definitely improve the experience. Dragging individual points is rather time-consuming while if you have some sort of brush that is pushing all points at once It'll save years of human lives.

**Comment by rphila** [comment]
A paintbrush tool with an eraser would be helpful for my purpose as well!

Using a polygon is tedious if you have a long worm-like region to segment, and the polyline does not capture the different widths. Having a paintbrush with an eraser tool to refine will make segmenting these regions more precise and quicker.

**Comment by reubenwenisch** [comment]
Is this feature available now?

**Comment by nmanovic** [comment]
@reubenwenisch , the patch has not been merged yet.

**Comment by noamzilo** [comment]
Any update on this? Our company is leaving CVAT over the lack of a brush tool, which will be expensive and unfortunate.
Is there an estimated date of release of a brush tool?

**Comment by nmanovic** [comment]
@noamzilo , we are working on the feature. Indeed there are several options if you want to use CVAT:
- Wait why we implement the feature. CVAT is free, thus it can be attractive for many users and companies
- Contribute the feature, help us to implement it.
- Pay us for some commercial support. Thus your requests will be a priority for us.
