### ISSUE TITLE
Unable to create task from zip archive located in connected shared folder

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#2677]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Permission error occurs when selected zip archive located on connected file share

### Expected Behaviour
Task is created successfully.

### Current Behaviour
```python
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 257, in _create_thread
    extractor = MEDIA_TYPES[media_type]['extractor'](
  File "/home/django/cvat/apps/engine/media_extractors.py", line 187, in __init__
    self._zip_source = zipfile.ZipFile(source_path[0], mode='a')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '/home/django/share/data/test.zip'
```

### Steps to Reproduce (for bugs)

1. Try to create a task with zip archive located in connected share

### Your Environment

- Git hash commit (`git log -1`): https://github.com/openvinotoolkit/cvat/commit/a440ef24f88749a99cc6eaaf434821b9b3a3ca60 
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by tralfamadude** [comment]
I have this same error when using png files (no zip). After I created a share that maps to a host level dir, I made a bash shell in the container to look at /home/django/share running as user django; surprisingly, I could not list the dir and the ownership was unusual:

drwxrwxr-- 3   1004    128 4096 Feb 26 00:29 share

Obviously, if a user and group show up as numbers here, that means they are not defined. It turns out, these numbers correspond to my account from the host OS. I made that directory world readable and the group is "docker". 

I tried to change these from inside the container, but that produces an error about read-only fs. 

WORKAROUND: host level directory (the share) must have world permission 5. Example: chmod -R 775 /mnt/share

**Comment by azhavoro** [comment]
@tralfamadude there is no documentation issue, this should be fixed on CVAT server code. I believe read permissions for the share should be enough, but currently this does not work for archives.
@vnishukov Could you please discuss this with the 3D feature developers?

**Comment by schliffen** [comment]
I git the same problem with the latest commit as well.

**Comment by tralfamadude** [comment]
@azhavoro thanks for responding. It would not hurt to state that 755 chmod bits are recommended. This seems like a docker level issue, I don't see how processes in the container can get around it since I could not list the bound dir as root inside the container without 775 chmod bits. 

Read level is not enough if one wants to use subdirectories; execute is needed to list dirs. I organize images by task and name a directory with the task name; this makes it easy to clean up after a task is finished.

**Comment by azhavoro** [comment]
> @azhavoro thanks for responding. It would not hurt to state that 755 chmod bits are recommended. This seems like a docker level issue, I don't see how processes in the container can get around it since I could not list the bound dir as root inside the container without 775 chmod bits.
> 

Probably you mounted share in the `ro` mode as described in the installation guide https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#share-path.

> Read level is not enough if one wants to use subdirectories; execute is needed to list dirs. I organize images by task and name a directory with the task name; this makes it easy to clean up after a task is finished.

Of course the execute bit is needed for directories, I mean read permission as docker mode for the mounted volumes.
