### ISSUE TITLE
How do I need to modify the CVAT that can be deployed on my own server like onepanel. I want to modify the model file. Automatically annotate the video with your own trained model.

### ISSUE THREAD

**Issue by kingmacth** [opencv/cvat#414]
How do I need to modify the CVAT that can be deployed on my own server like onepanel. I want to modify the model file. Automatically annotate the video with your own trained model.

**Comment by nmanovic** [comment]
@kingmacth , in general you don't need to modify CVAT to deploy it on your own server. You need to create a separate file (e.g. docker-compose.yml) for all your settings and put them into the file. See here an example: https://github.com/opencv/cvat#advanced-settings.

I will close the issue because it is a question and we want to keep here only real issues or feature requests for CVAT. If you have other questions don't hesitate to ask them here: https://gitter.im/opencv-cvat/public
