### ISSUE TITLE
Importing dataset in cvat format loses angle

### ISSUE THREAD

**Issue by dreambit** [opencv/cvat#4378]
When i export my dataset in cvat format and then import it - all bboxes are without angle(angle is reset to 0)

**Comment by bsekachev** [comment]
Might be related with #4745, but I am not sure.

**Comment by bsekachev** [comment]
@zhiltsov-max 

Looks like here we need fix on datumaro side. I expect ``attributes`` field to contain ``rotation`` as it implemented for ``occluded`` after this line ``Dataset.import_from(tmp_dir, 'cvat', env=dm_env)``. 

<img width="786" alt="image" src="https://user-images.githubusercontent.com/40690378/199425565-67db1e46-5473-4541-aab5-9984aa08a120.png">

The bug happens when we export/import a project.

**Comment by zhiltsov-max** [comment]
@yasakova-anastasia, please check this issue.
