### ISSUE TITLE
Issue box rotation is not applied on rotated rectangles

### ISSUE THREAD

**Issue by amirdana** [opencv/cvat#4379]
you can see it here

![gnome-shell-screenshot-M8YYH1](https://user-images.githubusercontent.com/54178517/155274414-9b31dfa0-1ffe-48ba-9777-2c35fad7ebd1.png)

**Comment by bsekachev** [comment]
Thank you for the report

**Comment by zzhuncle** [comment]
Could you tell me how to use the rotated rectangles function.My version didnot have this function.Thanks very much!

**Comment by bsekachev** [comment]
@zzhuncle 

So, you probably need to update CVAT if it is not supported.

**Comment by zzhuncle** [comment]
could you tell me when you download the cvat reposit? Do you use the develop branch or the master branch? Thanks very much!

**Comment by bsekachev** [comment]
By default it is develop branch, to build CVAT from source code you need to add ``-f docker-compose.dev.yml`` to built command. 
Otherwise installation fetches the latest built releases from dockerhub.

**Comment by zzhuncle** [comment]
Thanks very much! But I have some problems to build CVAT images myself because my Internet is poor and I have tried many times to build images but it always crushed in the middle. Could you upload your latest images into  https://hub.docker.com/ and publish the link? Thus others can use it. Thanks very much! If you did not want to upload, it will be ok too. All in all, thanks very much!

**Comment by bsekachev** [comment]
@zzhuncle We will have a release soon (I hope this week). The image will be updated.

**Comment by zzhuncle** [comment]
> @zzhuncle We will have a release soon (I hope this week). The image will be updated.

You are so nice, and thanks very much!
