### ISSUE TITLE
[Feature] Convert rectangle shape to rectangle track 

### ISSUE THREAD

**Issue by MyronRodrigues-StreetDrone** [opencv/cvat#4634]
Is there a way to convert rectangle shape (detection) to track shape (for interpolation) ?

I have detections from auto-annotation but they are all in shape rectangle. If I can convert them to track then it becomes easy to propagate the annotation in new frames.

**Comment by bsekachev** [comment]
Hi, for your case we have ReID model (https://github.com/openvinotoolkit/cvat/tree/develop/serverless/openvino/omz/intel/person-reidentification-retail-300/nuclio). 

It merges automatically shapes from different frames to tracks, but actually I am not sure it works now, because it is used extremely rarely. Anyway, need to think about how this case can be efficiently solved, without manual transformation each object into track.

**Comment by Badrick16** [comment]
This should be a case if you upload annotations, because when you import an older dataset, you lost the keyframes and track function. At least for CVAT image format.

**Comment by bsekachev** [comment]
1. CVAT for images is not supposed to be used for tracks 
2. Even if it is used, how is it possible to lost keyframes?  Could you please provide example?

**Comment by nathantew14** [comment]
> 1. CVAT for images is not supposed to be used for tracks

what should be used then? the tracks become basic shapes after i export and import into another task
