### ISSUE TITLE
CVAT server down for 2 days

### ISSUE THREAD

**Issue by shlokshah7** [opencv/cvat#4715]
Hello, 
Can the CVAT issue be resolved soon. We can't even get through the log in page and therefore cannot retrieve any previously saved data.

**Comment by nmanovic** [comment]
@shlokshah7 , I totally understand you, but my team doesn't have permissions to fix the issue now due to https://github.com/openvinotoolkit/cvat/issues/4444#issuecomment-1141066544. Please send your questions and complains to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum. I hope that they will help.

**Comment by nmanovic** [comment]
@shlokshah7 , I really believe that in a month or so the suitation will be clear and CVAT will be maintained again.

**Comment by nmanovic** [comment]
@RRaphaell , @sourabmaity , Please send your questions and complains to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum.

**Comment by nmanovic** [comment]
@RRaphaell , @sourabmaity , @shlokshah7 , CVAT.org should be online in the nearest future. But you can try this one: https://app.cvat.ai/. It is support by CVAT core team.

**Comment by ActiveChooN** [comment]
@shlokshah7, @sourabmaity, @RRaphaell, hi, CVAT is up and running.

**Comment by RRaphaell** [comment]
Hi @ActiveChooN
I still can't create an account or reset password 
![image](https://user-images.githubusercontent.com/74569835/182405248-f090325e-fdae-470f-b902-d9400dab3a0c.png)

**Comment by nmanovic** [comment]
CVAT.org is up and running in read only mode. Please move your tasks to [CVAT.ai](http://cvat.ai/)
