### ISSUE TITLE
Could not login on server~ open the browser console to get details

### ISSUE THREAD

**Issue by Akashbhukt** [opencv/cvat#4718]
Please help. Which code do I need to run and how to run? Where to run.
![Screenshot_2022-06-26-00-34-00-18](https://user-images.githubusercontent.com/108195128/175787277-bdb49b4a-3ba0-438c-88f6-334041955443.jpg)

**Comment by yoonsang0910** [comment]
This is happening for a week now, I'm not sure it's me or the server. Console says (Error: Request failed with status code 500; Server Error).

**Comment by Eduardof0nt** [comment]
Same here! I need to train an employee to work on a dataset for a proyect and it's been a week and no luck... Please someone help!

**Comment by yoonsang0910** [comment]
was in a hurry and ended up just using LabelMe. Didn't really like it but was simple enough to quickly install and start annotating. cvat really needs to have some server maintenance..

**Comment by EricEdmundXiang** [comment]
Same too ...

**Comment by nmanovic** [comment]
@EricEdmundXiang , @yoonsang0910 , @Eduardof0nt , @Akashbhukt , I totally understand you, but my team doesn't have permissions to fix the issue now due to https://github.com/openvinotoolkit/cvat/issues/4444#issuecomment-1141066544. Please send your questions and complains to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum. I hope that they will help.

**Comment by ChalaniEkanayake** [comment]
Same issue

**Comment by yustiks** [comment]
I also have the same issue
