### ISSUE TITLE
Updating Task Select Attribute Options

### ISSUE THREAD

**Issue by MatthewMcLeod** [opencv/cvat#477]
Hello, thanks for making this wonderful tool.

I created a task and added a select=type attribute. During the tagging, I realised I would like to add an additional attribute as one of the options. I used the Update Tag button and placed the additional field in the "expand the specification here". When I reload my video, all the previous selected attributes for the identified entities are missing/lost in the UI. 

How can I dynamically add options to an attribute selection field? I would prefer to not use the empty text field.

To recreate this, just simply follow the procedure I described. I am using Ubuntu 16.04 with the  current version of CVAT.

**Comment by nmanovic** [comment]
@MatthewMcLeod , it seems I missed the issue. Do you still have it? It is definitely possible to add more labels and attributes. Please ask a specific question about your case on gitter and I will provide information how to specify them.

I will close the issue for now. Please don't hesitate to re-open it if you want to discuss it here instead of gitter.

**Comment by MatthewMcLeod** [comment]
It was a misuse on my part of the UI. I understood how it use the field and it works fine now. Thanks!

**Comment by kgloveyou** [comment]
> It was a misuse on my part of the UI. I understood how it use the field and it works fine now. Thanks!

Hello, I came across the same problem. How can I dynamically add options to an attribute selection field?
