### ISSUE TITLE
How to train 3D Object Detection Model with exported custom labeled dataset?

### ISSUE THREAD

**Issue by RafaelsNeurons** [opencv/cvat#4801]
Hey :),
I‘m trying to Train a 3D object detection Model with my custom 3D dataset created with cvat.
But I‘m confused I exported in Kitti formate but was Not able to do transfer-learning with it. 
Can somebody recomment a model which takes the exported Data as training?

Thanks :)

**Comment by holtvogt** [comment]
Usually, in order to train a KITTI-based model, the KITTI format requires label files for each point cloud or image frame in the following structure:

000042.txt:
>type<sub>0</sub> truncated<sub>0</sub> occluded<sub>0</sub> alpha<sub>0</sub> bbox<sub>0</sub> dimensions<sub>0</sub> location<sub>0</sub> rotation_y<sub>0</sub> score<sub>0</sub>
>type<sub>i+1</sub> truncated<sub>i+1</sub> occluded<sub>i+1</sub> alpha<sub>i+1</sub> bbox<sub>i+1</sub> dimensions<sub>i+1</sub> location<sub>i+1</sub> rotation_y<sub>i+1</sub> score<sub>i+1</sub>
>..
>type<sub>n</sub> truncated<sub>n</sub> occluded<sub>n</sub> alpha<sub>n</sub> bbox<sub>n</sub> dimensions<sub>n</sub> location<sub>n</sub> rotation_y<sub>n</sub> score<sub>n</sub>

| Values |      Name      |  Description |
|:----------:|:-------------:|------|
| 1 | type |Describes the type of object: 'Car', 'Van', 'Truck', 'Pedestrian', 'Person_sitting', 'Cyclist', 'Tram', 'Misc' or 'DontCare' |
| 1 | truncated |Float from 0 (non-truncated) to 1 (truncated), where truncated refers to the object leaving image boundaries |
| 1 | occluded | Integer (0,1,2,3) indicating occlusion state: 0 = fully visible, 1 = partly occluded 2 = largely occluded, 3 = unknown | 
| 1 | alpha |  Observation angle of object, ranging [-pi..pi] | 
| 4 | bbox |2D bounding box of object in the image (0-based index): contains left, top, right, bottom pixel coordinates | 
| 3 | dimensions | 3D object dimensions: height, width, length (in meters) | 
| 3 | location | 3D object location x,y,z in camera coordinates (in meters) | 
| 1 | rotation_y | Rotation ry around Y-axis in camera coordinates [-pi..pi] | 
| 1 | score | Only for results: Float, indicating confidence in detection, needed for p/r curves, higher is better. |

With that being sad, the information you receive from the CVAT export is in KITTI Raw Format 1.0 which will generate a `tracklet_labels.xml` file from which you need to convert the corresponding tag values to the KITTI format mentioned above. I recently created an issue to make sure I understood that properly. You can have a look [here](https://github.com/open-mmlab/mmdetection3d/issues/1702). I hope that helps! :)

**Comment by RafaelsNeurons** [comment]
Thank you very much! This was exactly what I was looking for. I will also try it with MMDETECTION3D.

So the worksteps are:

1. Label point cloud .pcd data with cvat
2. Export the dataset in kitti formate
3. Create manually the label files like for example 000042.txt for every point cloud in my data set
4. train a model with mmdetection3d

Or did I forgot a step ? :)


Again, thank you very much!

**Comment by holtvogt** [comment]
> 3. Create manually the label files like for example 000042.txt for every point cloud in my data set

Correct. The CVAT export always provides a `frame_list.txt` which basically contains a dictionary with frame index in ascending order and its corresponding `pcd` file name as value. That comes in handy when trying to automate that conversion. I have already written a tracklet parser based on the CVAT export. If I'm not too busy, I'll be able to publish it on GitHub (I'd get back to you if it might be helpful) :)

> 4. train a model with mmdetection3d

That's actually a huge point as you'll have to dig deep into the documentation and write your own dataset configuration. But yes, that's also correct.

**Comment by bsekachev** [comment]
That is not exactly CVAT issue, but I hope you were helped :)

**Comment by AJAY31797** [comment]
Hi, 

I have a related question, so I'm not adding it as a new issue. I have annotated some point clouds using CVAT. On understanding the KITTI annotation format, I came to know that the level of occlusion also has to be defined (something like 0,1,2,3). I was wondering how can I set the occlusion for 3D point cloud annotation. I saw the documentation page on 3D annotation, but nothing related to occlusion is discussed there. Is it done by clicking on the icon highlighted in the screenshot below? But it does not provide any way to set the level of occlusion. 
![image](https://github.com/opencv/cvat/assets/53423573/3e09a5e5-5cc4-499a-9ebf-5a834a3ecf4f)

Many thanks. 

Best Regards,
Ajay

**Comment by bsekachev** [comment]
You can add any custom attribute to your label and annotate it.
For example a SELECT with values: 1,2,3,4

**Comment by holtvogt** [comment]
@bsekachev Is it possible to integrate the parser into the CVAT export for KITTI related tasks? It would solve some convertion pain :)

**Comment by AJAY31797** [comment]
Thanks @bsekachev.
