### ISSUE TITLE
AI tracking tool is one frame late

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4870]
When using the AI tracking tool SiamMask (or any other tracking tool), the tracker is always one frame late. 

E.g.: 
1) I draw a bounding box at frame 0, then I press F to proceed to the next frame. 
2) Now the tracker is running initialization (with frame 0) and tracking step (also **incorrectly** with frame 0) 

Issue by @dschoerk

**Comment by dschoerk** [comment]
already fixed in commit 
https://github.com/opencv/cvat/commit/7e20b279afc2baa84f430296cc5e6820cf3ee6e2#diff-9d33e179bed693eec6521ca5b99cffd11305648d6f0390b6d009cb829892d59d

line
https://github.com/opencv/cvat/blob/7e20b279afc2baa84f430296cc5e6820cf3ee6e2/cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx#L759

**Comment by nmanovic** [comment]
@dschoerk , I will close the issue in the case.
