### ISSUE TITLE
Building images using Dockerfile 

### ISSUE THREAD

**Issue by venki-lfc** [opencv/cvat#4893]
### My actions before raising this issue
- [ X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ X] Searched [past issues](/issues)

Good day,
The linux system I am working on does not support avx and therefore there was a trouble in creating superuser. I browsed through one of the issues and the [solution](https://github.com/opencv/cvat/issues/2123#issuecomment-1184990539) was that I install non-avx TensorFlow by adding `RUN python3 -m pip install https://tf.novaal.de/btver1/tensorflow-2.8.0-cp38-cp38-linux_x86_64.whl` in the Dockerfile. 

My doubt is, when I build this [Dockerfile ](https://github.com/opencv/cvat/blob/develop/Dockerfile) using `docker build -t cvat_test:latest -f Dockerfile` what image am I exactly creating? Is it `cvat_server` ? How shall I use the image(s) I get from this Dockerfile to make the CVAT run? 

Any help would be appreciated. Thank you very much.

### Context
Trying to build the Dockerfile with an added non-avx tensorflow version because the PC doesn't support avx. 

### Your Environment
- Docker version `docker version`: 20.10.16
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem: https://github.com/opencv/cvat/issues/2123

**Comment by venki-lfc** [comment]
Building the Dockerfile gives me three images. 
1. cvat_test:latest - The name I gave while building the Dockerfile
2. none
3. ubuntu
![image](https://user-images.githubusercontent.com/60582874/187909190-811b7216-0647-4687-9a71-30f56658d52d.png)

I suppose the non-avx tensorflow is installed on either cvat_test:latest or none. Could you please tell me what do these images mean and how do I make CVAT running by using them?

**Comment by azhavoro** [comment]
@venki-lfc Hello
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml build cvat_server` command builds `cvat_server` new image on your machine
After that you can run containers as usual `docker-compose up -d`
But I beleave that the issue is not related with tensorflow, in case of your machine doesn't have avx support you just cannot use import/export in TF format and CVAT should be started correctly. Most likely there are some other packages/libraries that require avx support. Could you provide logs with the issue?

**Comment by azhavoro** [comment]
I hope the issue is resolved
