### ISSUE TITLE
Why not using MongoDB to store annotation info or meta info?

### ISSUE THREAD

**Issue by DonYum** [opencv/cvat#496]
Apparently, XML is nice. But it's limited by storage. So many magic capacity is locked!
Putting the data on the cloud should be a good idea.

MongoDB is a NoSQL DB, which is very popular now since it has lots of flexibility to use.
If we use MongoDB to storage all annotation/task/image meta/history/user info, we will benifit a lot.
And lots of playing method about CVAT will be unlock.

Think about it. It's very worthwhile!

**Comment by nmanovic** [comment]
Hi @DonYum ,

Could you please elaborate a little bit more? To store `annotations, users, image meta info` we use PostgreSQL or sqlite (it depends on configuration). XML is output format if you want to dump annotations.

**Comment by DonYum** [comment]
I'm a CV data management engineer. We have more than 60 million images for deep learning.
For these data, we need mannually label or automatically prelabel them, and for badcase, we need label them again. The process is complex.
And there are many kinds of annotation type(e.g., object-det, classify, face-attribution, keypoint, reid...). One type has one annotation format, so you'll find using RDBMS(e.g., MySQL, SQLite, PostgreSQL) is annoying, because you need design suitable and kinds of schema carefully and adustment is difficult.

Storing Annotation is the base architecture, good design make code clean and easily reusing.
So we spent lots of time to investigate.
In the end, we choose MongoDB.

MongoDB use bson type, which you can regard as bin-json, to store info. It is schema-less, so it's very suitable for many kinds of annotation record.
Furthermore, with Mongoengine, one kind of ORM for python, we can easily use MongoDB.

FYI.

**Comment by nmanovic** [comment]
@DonYum , could you please describe your current pipeline (from raw data to a training dataset for a 
DL model) and which new features in CVAT will help your project? For example, nobody needs CVAT XML format. Many people need Pascal VOC, MS COCO, TF records, mask formats because finally they use such annotations to train a DL model. If you need to implement some analytics around your dataset I agree that it makes sense to use a DB. For example, internally we have ELK stack (elasticsearch is also used to store JSON documents) which is used to provide statistics and analytics for different datasets.

**Comment by nmanovic** [comment]
@DonYum, please don't hesitate to submit specific feature requests to support required functionality. For now I will close the issue because it isn't a feature request and just a discussion. Next time maybe better to discuss such questions on our gitter channel.
