### ISSUE TITLE
Heavy Ram usage while exporting Dataset

### ISSUE THREAD

**Issue by mexxBf** [opencv/cvat#5528]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

I'm trying to export my dataset. It consists of 70 Videos in hd, or wqhd and is labled with automatic labeling. 

My PC has 64GB of Ram, but fails to export the dataset, because its running out of memory. Error message says it fails to export frame 026543. I guess its just the first frame that didn't fit in memory.

I exported one task, but even there the exported zip was 1.2 GB even though the video is only 10 mb. 

### Expected Behaviour
Exporting my dataset, preferably only the annotated frames.
### Current Behaviour
Error 500 frame xxxxxxx

### Possible Solution
several things would be possible.

Exporting jpg instead of PNG maybe?
Export one video after another, temp save the result and go to the next.
Export only the annotated frames

### Steps to Reproduce (for bugs)

Huge? amount of video files. And export them

### Context
The only way I'm able to export my dataset is exporting all videos job after job. 

Thank you

**Comment by zhiltsov-max** [comment]
Hi,

When exporting videos, the frames are exported as separate images, so even a tiny video file can be unpacked into a very big dataset. As a workaround, you can export just the annotations, then download the frames separately (described [here](https://github.com/opencv/cvat/issues/5449#issuecomment-1361876380)). The image file format won't play a big role, because we're exporting frames with the original quality by default, both jpg and png will be quite big.
