### ISSUE TITLE
Can I retrain the pre-trained model on the CVAT Dashboard site?

### ISSUE THREAD

**Issue by otsukaoly** [opencv/cvat#559]
My image data doesn't match pre-trained models. 
I want to execute the automatic segmentation function or the semi-automatic segmentation function of CVAT using the customized model.

I confirm the customized model referring below.
https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Deep_Learning_Inference_Engine_DevGuide.html

Can I retrain the pre-trained model on the CVAT Dashboard site?
Or can I make the customized model on the CVAT Dashboard site?
Or is there easy procedure to make the customized model?

The type of annotation is segmentation.

**Comment by nmanovic** [comment]
@otsukaoly ,

Probably I don't understand the request completely but CVAT doesn't train models. You can upload your model and use it to automatically annotate data. CVAT cannot modify the model.

Let's move the question to our [gitter channel](https://gitter.im/opencv-cvat) channel. I will close the issue because it is a question.

**Comment by otsukaoly** [comment]
Thank you for introducing the gitter site.
