### ISSUE TITLE
Can not upload files to the task

### ISSUE THREAD

**Issue by Idnan** [opencv/cvat#5726]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hi, I am trying to upload files to the task via rest API. But it's not uploading files. Basically, I am uploading files using `server_files` and which requires sending two API calls. First with `Upload-Start: true` header and then second with `Upload-Finish: true` header. So sending the first API with `Upload-Start: true` is successful but the second API call with `Upload-Finish: true` timesout.

Here's my code:
```
const attachmentsData = new FormData();
attachmentsData.append('use_zip_chunks', 'true');
attachmentsData.append('use_cache', 'true');
attachmentsData.append('sorting_method', 'lexicographical');
attachmentsData.append('cloud_storage_id', '1');
attachmentsData.append('storage', 'cloud_storage');
attachmentsData.append('image_quality', imageQuality);
attachmentsData.append('chunk_size', chunkSize);
for (let i = 0; i < images.length; i++) {
  attachmentsData.append(`server_files[${i}]`, images[i]);
}
attachmentsData.append(`server_files[${images.length}]`, 'manifest.jsonl');

const { data: attachments1 } = await axiosClient.post(
  `${host}/api/tasks/${task.id}/data/`, //
  attachmentsData,
  {
    headers: {
      Authorization: `Token ${authToken}`,
      'Upload-Start': true,
      ...attachmentsData.getHeaders(),
    },
  },
);
console.log(attachments1);
console.log('first done');
const { data: attachments2 } = await axiosClient.post(
  `${host}/api/tasks/${task.id}/data/`, //
  attachmentsData,
  {
    headers: {
      Authorization: `Token ${authToken}`,
      'Upload-Finish': true,
      ...attachmentsData.getHeaders(),
    },
  },
);
```

### Your Environment

- Git hash commit (`git log -1`): 86a0d51430fa090b855c196797c14d877492e59b
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.22
- Are you using Docker Swarm or Kubernetes? Docker Swarm
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS

**Comment by zhiltsov-max** [comment]
Hi, I see several possible problems in this code snippet. 
- Uploading `server_files` doesn't require separation into multiple requests (since you're not uploading anything actually and just specify server paths), though it can be done this way too.
- Authorization requires [2 headers (check the Authorization block)](https://app.cvat.ai/api/docs/#tag/auth/operation/auth_create_login): one for session token and another for CSRF token. You can find both of them in the response values and cookies. You can find auth examples [here](https://github.com/opencv/cvat/blob/develop/tests/python/rest_api/test_auth.py#L78-L79).

The rest looks fine. To troubleshoot this, I recommend:
- to try to check the server logs using `docker logs cvat_server`. 
- check if this works with our [CLI](https://opencv.github.io/cvat/docs/api_sdk/cli/) or UI
- could you please tell how many files are you requesting?
