### ISSUE TITLE
When the amount of job frames is too large, the loading is slow. How to load data in batches?

### ISSUE THREAD

**Issue by kgloveyou** [opencv/cvat#5806]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.creat a job contains 10000 frames
2.annotate the job,then reopen it
3.it will cost more then 10s to loading the job

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Data already loaded in batches (or chunks). Chunk size can be specified when creating a task.  

Please, refer to the documentation: https://opencv.github.io/cvat/docs/manual/basics/create_an_annotation_task/#advanced-configuration 

Also there are multiple things can affect task opening time, like size, bandwidth, number of annotations, CPU performance, etc.

**Comment by neekey** [comment]
i'm having the same issue and after inspecting the network, the slowness seems to be due to the whole job plus all the images are included into the same request:

<img width="626" alt="image" src="https://github.com/cvat-ai/cvat/assets/499870/486bda6d-e05f-4945-9250-4f2a0d870950">

what is the reason to pack all the images into one request response payload instead of just loading the images individually in each image annotation?
