### ISSUE TITLE
Question about skeleton annotation in coco format

### ISSUE THREAD

**Issue by SRAMXXX1** [opencv/cvat#5904]
It's great to see cvat introducing skeleton labeling. This feature is easy to use. In cvat document, it says "Moreover, each the skeleton point can be dragged itself. After dragging, the wrapping bounding box is adjusted automatically, other points are not affected"(https://opencv.github.io/cvat/docs/manual/advanced/annotation-with-skeletons/editing-the-skeleton/)

But there is a problem, how can I fix the size of the bbox？ When I drag the points, I don't want the size or position of the bbox to change. In my pose detection task, the 'bbox' should envelop the whole person, not just the set of enveloped points. 

I tried grouping a skeleton and a rectangle and exporting it to coco keypoint format, but apparently that didn't achieve my goal either.

I was using coco annotator(https://github.com/jsbroks/coco-annotator) and MMpose(https://github.com/open-mmlab/mmpose). The position size of the bbox is not affected by the point position. Points can even be marked outside the rectangular box.

I sincerely hope to get a way to customize the bbox position and size. If this is not possible now, I would appreciate if your development team would consider this request

**Comment by bsekachev** [comment]
Okay, I see. CVAT skeletons can support only points now.

But it should work with rectangles & grouping feature. You told the following:

> I tried grouping a skeleton and a rectangle and exporting it to coco keypoint format, but apparently that didn't achieve my goal either.

What was wrong in this case?

**I tried to create a skeleton, a rectangle around it, and grouped them. In annotation file with COCO Keypoints I see:**

<img width="330" alt="image" src="https://user-images.githubusercontent.com/40690378/226929397-5385d75c-ac11-4248-b84c-a2cd796340b0.png">

**In annotation view with grid 200px X 200px I see:**

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/40690378/226930420-5eb9b909-cd9c-4dd3-a3c8-3b933d441b13.png">

So, looks like box coordinates in annotation file are correct.

**CVAT Version is:**
<img width="578" alt="image" src="https://user-images.githubusercontent.com/40690378/226930647-7f8f82f2-109f-4bb7-a633-23dabf0dc4b1.png">

**Comment by SRAMXXX1** [comment]
>But it should work with rectangles & grouping feature. You told the following: 'I tried grouping a skeleton and a rectangle and exporting it to coco keypoint format, but apparently that didn't achieve my goal either.'

Hi, I tried again and the method was able to get the data I wanted in the 'annotation' field. But this in only a temporary solution, I don't know if this feature will be looked at in future updates from cvat. I guess it's not particularly difficult to implement custom box sizing packages. But this feature is really useful.

>Bounding box you see is "virtual". It is not a part of annotations and the main purpose of this bounding box is to drag/resize the whole skeleton.

In addition, I would like to suggest the cvat team to revise the following 'skeleton' related documentation. After all, the virtual box in the monthly UI is very confusing, so maybe someone is using this feature right now and not paying attention to the specifics of the 'bbox' value in the markup file.

Finally, thank you sincerely for your reply, it did help me!

**Comment by anantyadav0** [comment]
I want this project because study area of my is related to this

**Comment by bsekachev** [comment]
Now the wrapping bbox is visible only when an object is activated. Hope it is less confusing.

**Comment by devvaibhav455** [comment]
I tried to use the functionality recently and think that this issue is happening again. I am using the tool present on the web interface https://app.cvat.ai/
Below image contains both the bbox that I selected myself and the one through the skeleton with the keypoints.

![Screenshot from 2024-01-11 11-30-23](https://github.com/opencv/cvat/assets/91839547/fa201786-81ce-4fc3-90d7-9f1709381d1e)

I am exporting to the `COCO Keypoints 1.0` format and as can be seen from the below image, the bbox co-ordinates are clearly not from the rectange that I selected but from the skeleton.
![image](https://github.com/opencv/cvat/assets/91839547/13f544d8-8194-4b2d-bcf6-ca00e3c24f61)

The web version shows me the below version.

`Server version: 2.10.0
Core version: 14.0.3
Canvas version: 2.19.1
UI version: 1.61.1`

**Comment by jwee1369** [comment]
@devvaibhav455  I had this problem too, the coco keypoint export seems to disregard the bbox of the additional rectangle altogether, only using the skeleton bbox. I would just use the CVAT video 1.1 export format and post process to whatever format you need

**Comment by devvaibhav455** [comment]
@jwee1369 : i figured out the problem through someone's suggestion on Git Hub. The skeleton and bbox need to be grouped. If you do that way and then export again, you will see the correct bbox co-ordinates.

**Comment by jwee1369** [comment]
@devvaibhav455  Thanks for the tip, works now, this link was helpful too

[Grouping in CVAT](https://www.youtube.com/watch?v=m8bB9f23wLs)

**Comment by twilson1111** [comment]
Hello, when trying to convert from Roboflow "COCO Keypoints" export to CVAT, I am running into the above problem where CVAT does not import the BBOX from the Roboflow output.  I am trying to use CVAT for going forwardd because Roboflow is too expensive, but I cannot figure out how to do the import.  Would it be possible to change the COCO Keypoints import type in CVAT to also import the BBOX as an additional label as part of the "person"?  My end case is I want to train models for YoloV8 Pose, which expects the data in this format.
