### ISSUE TITLE
Support ownCloud as cloud storage provider

### ISSUE THREAD

**Issue by bruluk5w** [opencv/cvat#6028]
### My actions before raising this issue
- [y] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [y] Searched [past issues](/issues)

We are annotating a dataset with multiple possibly large videos. Task creation takes forever for large videos (>5GB). I saw that CVAT uses manifest files which can be generated in advance. I thought that generating these will be my solution. However, I have the dataset currently on a shared volume and it seems to not be possible to select the manifest file when creating a task. I had a look to the code and indeed the UI only allows to use manifest files for image datasets (Is this intended or should this also work for videos?).
Further reading though the documentation made me realize that apparently the intended way is having the manifest files and videos on some cloud storage, which would also be beneficial for us.
However, we use an internal ownCloud instance.

In case using a cloud storage is the right intended way to use the optimization that manifest files provide for videos, would it make sense to implement support for ownCloud as a cloud storage provider?

I am by no means good at frontend stuff but there are other cloud providers already implemented and I may have some time on my hand to do it within a university project.

Thank you and looking forward to your feedback.

**Comment by Marishka17** [comment]
@bruluk5w, Hello,

It's possible to use the manifest file for a video from share point.
But I should say that it's suite not for all videos, only for those that have an appropriate number of I frames.
You can generate the manifest by command:
```bash
docker run -it --rm -u "$(id -u)":"$(id -g)" \
  -v ~/Documents/data/:${HOME}/dir_with_video/:rw \
  --entrypoint '/usr/bin/bash' \
  cvat/server \
  utils/dataset_manifest/create.py --output-dir ~/dir_with_video/ ~/dir_with_video/video.mp4
  ```
You can use `--force` option If a video doesn't contain enough key frames but it can work not optimally.
Please see the documentation about manifest [here](https://opencv.github.io/cvat/docs/manual/advanced/dataset_manifest/#examples).

Once you've created the manifest file for your video you'll need to move it to share point.
Then you can create a task e.g. using CVAT SDK this way:
```python
from cvat_sdk import make_client
from cvat_sdk.core.proxies.tasks import ResourceType

with make_client(host="localhost", port=8080, credentials=('user', 'password')) as client:
    task_spec = {
        "name": "example task",
        "labels": [
            {
                "name": "car",
            }
        ],
    }

    task = client.tasks.create_from_data(
        spec=task_spec,
        resource_type=ResourceType.SHARE,
        resources=['video.mp4', 'manifest.jsonl'],
    )
    print(task)
```
Now you cannot create a such task in CVAT UI, it's a bug and will be fixed in [PR](https://github.com/opencv/cvat/pull/6074).
Please, see the SDK documentation [here](https://opencv.github.io/cvat/docs/api_sdk/sdk/highlevel-api/).

**Comment by pktiuk** [comment]
Maybe instead supporting OwnCloud it would be better to add support a bit more universal protocol used by OwnCloud like WebDAV?
