### ISSUE TITLE
Allow filtering images with some specific condition in a job list

### ISSUE THREAD

**Issue by yf-yang** [opencv/cvat#6121]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Scenario: Suppose I have a pending job, when I am labeling/reviewing the job, I may want to first shrink the image list to "images containing cars", then shrink the image list to "images tagged as raining", and view those images that match the filter only.

As far as I know, the filter of an annotation filters specific labels for a given image, the filter of project/task/job... filters metadata, but I can't find a filter over a list of data.

Is it possible, or will it be supported?

**Comment by bsekachev** [comment]
Hi @yf-yang.

It is supported. Just apply a filter like: Label === "something" and then use arrow left/right to navigate instead of D, F keys.
It will navigate to those frames which contain at least one object satisfying a filter. 

Another option is to click "Next", "Prev" button by right click to see navigation options. Not really intuitive, we know.. 
<img width="207" alt="image" src="https://github.com/opencv/cvat/assets/40690378/5c364804-fd25-435e-9145-4616e5480fff">

**Comment by yf-yang** [comment]
Nice, thanks!
