### ISSUE TITLE
Could not fetch preview for the Cloud Storage-S3 Bucket

### ISSUE THREAD

**Issue by sidu21** [opencv/cvat#6144]
### My actions before raising this issue

- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

I don't think it can be reproduced

### Expected Behaviour

I should be able to connect to S3 Storage and import Data

### Current Behaviour

I was successfully able to connect to S3 but I can't view the files.

### Context

I was trying to import data for labeling in CVAT online

![image](https://github.com/opencv/cvat/assets/125720418/fed87ed3-4210-4e72-952e-a8986fa95fb1)

![image](https://github.com/opencv/cvat/assets/125720418/34239fb5-7722-4605-a64f-11746728a0b4)

**Comment by bsekachev** [comment]
@Marishka17 
Do you have any ideas?

**Comment by Marishka17** [comment]
@sidu21, Hi,
Could you please share the example of the manifest structure that is attached to the cloud storage?
But the problem with getting a preview should not affect to the ability to import data, could you please describe all steps for data importing from cloud storage that you did and the problem after that?

**Comment by iongion** [comment]
Is there a guide somewhere on how to use cloud storage ? It is a bit confusing

- What is the manifest for ?
- I have multiple projects with many tasks that have a single video, this video is stored in s3
- What I am doing now is use s3fs with fuse, but I am noticed it will soon consume all disk space on the machine, why is this happening ?

My procedure is:

1. Take the video and make it seek-able with faststart/moovatom using ffmpeg
2. Process it with `dataset_manifest.create_manifest` to generate the `manifest.jsonl` - I don't understand what is needed for
3. Now I upload the video + the manifest to s3
4. I mounted the s3 bucket on the cvat machine as an s3 fuse drive
5. I also defined the cloud storage to use the same s3 bucket (let's say `cloud_storage_id = 1`)
6. I create project + task + job programmatically using the sdk, looking something like this

```python
CLOUD_STORAGE_MOUNT = "s3-fuse" # This will make it use the mount on the cvat machine available at `/home/django/share/s3-fuse`
project_id = 1
video_path = "videos/1/video.mp4" # this is s3://my-bucket/videos/1/video.mp4
manifest_path = "videos/1/manifest.jsonl" # this is s3://my-bucket/videos/1/manifest.jsonl
resources = [video_path, manifest_path]
s3fuse_resources = [f"{CLOUD_STORAGE_MOUNT}/{res}" for res in resources]
client.tasks.create_from_data(
            spec={"name": name, "project_id": project_id, "image_quality": 100, "use_cache": False, "use_zip_chunks": False, "cloud_storage_id": 1},
            data_params={"sorting_method": "lexicographical"},
            resource_type=ResourceType.SHARE,
            resources=s3fuse_resources
        )
```

Problems

- Disk space use is growing, the more videos I have in s3, the more disk space the django app/api machine is using
- I don't understand what cloud storage is doing / what it is meant for
- Does cvat cache the s3 fuse drive somewhere locally ?
- What would happen if I have 10 TB of videos in s3, will that need the cvat machine to have 10 TB disk space available ? because I can't make that available for the machine
- I am doing all wrong

**Comment by sidu21** [comment]
> 
Here's the example structure of manifest.jsonl :
```
{"version":"1.1"}
{"type":"video"}
{"properties":{"name":"video.mp4","resolution":[1280,720],"length":9322}}
{"number":0,"pts":0,"checksum":"5b5fcf1713ba3e014b01620a5daac892"}
{"number":128,"pts":128000,"checksum":"3e5406bd7f8f2ae5e6849eab082e93f2"}
{"number":256,"pts":256000,"checksum":"66c32e957abf249fdd2359a59cb0ea42"}
........................................................................................................................................................................
{"number":9088,"pts":9088000,"checksum":"a90cdcea3e19769001df9974da01c027"}
{"number":9216,"pts":9216000,"checksum":"73fa1b63b5e6ce3be83db3f29b331bdf"}
```

Steps I've folllowed to import data from cloud storage:

1. Create a folder with the video in it. 
2. Process it with dataset_manifest.create_manifest to generate the manifest.jsonl
3. Upload the video to s3 bucket.
4. Go to app.cvat.ai > Cloud Storages> Create Cloud Storage> Select AWS S3>Enter bucket name and credentials> Add manifest.jsonl file > Submit

After these steps, I getting the error I've mentioned previously.

**Comment by pathikspec** [comment]
I'm getting exact issue with images as well  @Marishka17 

<img width="375" alt="image" src="https://github.com/user-attachments/assets/e71056cd-d82a-4dee-abd2-1ae2d0644ea4">

Manifest: 
```
{"version":"1.1"}
{"type":"images"}
{"name":"00007ee8-34fe-4db6-8439-c_169116_0","extension":".jpg","width":1700,"height":2200,"meta":{"related_images":[]},"checksum":"2e478f7dc1da322fbaa6cfa38575c3e1"}
{"name":"0000dfc4-cc3a-443f-ad6c-3_160222_0","extension":".jpg","width":1700,"height":2200,"meta":{"related_images":[]},"checksum":"829b333cc082974f080f5ae60a85ccd6"}

```

**Comment by Marishka17** [comment]
Hi @pathikspec, could you please provide additional information?
- server version
-  server logs (in case of docker deployment: docker logs cvat_server &> cvat.log)
