### ISSUE TITLE
how carry param to task create page

### ISSUE THREAD

**Issue by liudaolunboluo** [opencv/cvat#6198]
I have a scenario where I generate several (such as 100) image download URLs in my own system, and then jump to the task creation page of CVAT. I don't want users to repeatedly enter these 100 URLs, but I want to automatically fill in these 100 URLs for remote sources. What should I do

**Comment by bsekachev** [comment]
1. Create tasks on you own and assign them for users
2. Create task, backup it, and let other users to restore it from backup
3. Use shared / cloud storages to upload data, users do not need to fill these 100 URLs if they are on the shared storage, for example they can only click one directory. 

This is not easy to suggest something concrete, because the scenario is not clear.

**Comment by liudaolunboluo** [comment]
> This is not easy to suggest something concrete, because the scenario is not clear.

Thank you very much for your answer. In a simple scenario, I will help users create a task without labels but with a job, and then let them add labels on the interface themselves. I will try creating it using the rest API, which can pass on the project_ ID is not passed to create labels, but after successful creation, entering the page does not add labels

**Comment by bsekachev** [comment]
@liudaolunboluo 

When you create a task within a project, the task does not have its own labels, it takes labels from the project.
