### ISSUE TITLE
A module to convert annotations to different formats 

### ISSUE THREAD

**Issue by nmanovic** [opencv/cvat#625]
## Description

Now we have a set of scripts which can convert annotations to different formats: https://github.com/opencv/cvat/tree/develop/utils

At the same time CVAT server can do the same task using REST API better. It would be good to extract the functionality into a separate module and implement only one script which uses the module. Old scripts should be removed.

The script should have input parameters:
- a directory with images
- meta information (labels, attributes)
- original annotations in some format

The script should output:
- modified annotations in a specified format

## Results
- [ ] Remove converter scripts from https://github.com/opencv/cvat/tree/develop/utils
- [ ] Extract the functionality to convert annotations into a separate module
- [ ] Implement one script which can convert annotations from one format to another

**Comment by ajayramezh** [comment]
As per my understanding, we just need to merge all those [util scripts](https://github.com/opencv/cvat/tree/develop/utils). Keep one as standard.

**Comment by labellson** [comment]
First of all, thanks for all the work done on CVAT.

I created a basic script to parse the XML. The script creates a Python object representing the information contained in the XML. For now, the `<meta>` and `<images>` tags are parsed but no the `<track>` tag. Anyways, it should be enough in order to use it as a common parser of the XMLs and then write the converters from then. If you want to use it, you can find it [here](https://github.com/labellson/cvat/blob/cvat_xml_parser/utils/parser.py)

**Comment by bsekachev** [comment]
@zhiltsov-max Looks like solution is Datumaro. Could you confirm and close the issue.

**Comment by zhiltsov-max** [comment]
It is.

**Comment by nmanovic** [comment]
Dataset management framework: https://github.com/opencv/cvat/tree/develop/datumaro

**Comment by kobic8** [comment]
> @kobic8, could you please describe the problem in more details? Did you try the `Segmentation Mask` format for VOC mask import?

Hello, thank you for the reply. I have a toy example of a single image with an annotation file that includes both bbox/labels and maks in Pascal VOC xml file. Since there was a problem with import process via CVAT, I am interested in "of the shelf" converter function from PAscal VOC to CVAT xml file.

I tried to perform the opposite process: to export from CVAT to Pascal VOC and I saw that it exports two files (not one) that includes a pointer file.
