### ISSUE TITLE
Serverless instance segmentation support

### ISSUE THREAD

**Issue by hardikdava** [opencv/cvat#6266]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

There are preatrined/custom models available from various packages like yolov5, yolov7, yolov8, yolact, etc which supports for instance segmentation. Currently, app is missing this feature.

### Possible Solution
- Use serverless functionality to use pretrained model to predict masks 
- CVAT app directly plots masks using automatic labeling functions

### Context
- SAM is fast but there is still human interaction needed.
- If we add extra model support and let the AI model to do it.

I can add this feature if I get the good documentation regarding masks response to app.

**Comment by bsekachev** [comment]
CVAT supports [multiple models](https://github.com/opencv/cvat#deep-learning-serverless-functions-for-automatic-labeling), some of them, like ``Mask RCNN`` can predict masks. So, the app has this feature.
CVAT.ai also supports integration with Huggingface and Roboflow services where a lot of other models exist.

We do not have a purpose to support all the models, because generally it is impossible. 
There is a manual on how to integrate your own models https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models

For sure, if you are ready to contribute a good model, you are always welcome to do it.
