### ISSUE TITLE
Missing Supervisor Config File

### ISSUE THREAD

**Issue by DPeled** [opencv/cvat#6414]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Building using the Dockerfile

### Expected Behaviour

Default CMD args suppose to be correct

### Current Behaviour

There's no such file `all.conf` in `supervisord` folder

### Possible Solution

Create such `all.conf` or fix the Dockerfile

### Context

Running self-build images fails

**Comment by bsekachev** [comment]
@azhavoro 

Is it a bug?

**Comment by azhavoro** [comment]
@DPeled  `all.conf' was deleted some months ago and its configuration was split into several files (see supervisord folder).
Currently we use the same image to run all the services with different ENTRYPOINTs and CMDs for different services.
Perhaps the default CMD should be removed because there is currently no way to run all the services in the same container.
What is the purpose of running containers manually instead of using the existing compose config as recommended in the documentation?

**Comment by DPeled** [comment]
Well, I've planned to run this according to the docker-compose, but since I'm working from a stand-alone network, I had to build and moreover import dependencies that weren't in the network before.

Therefore, before running all the services together, I wanted a check that the build was successful, and I encountered that error so I mentioned it out here.
