### ISSUE TITLE
I want to use GPU instead of CPU

### ISSUE THREAD

**Issue by erenuito** [opencv/cvat#6467]
I am using CVAT but it works with CPU, It is well but I want to work it faster, so I want to work with GPU(instead of CPU) How can I fix it?

**Comment by bsekachev** [comment]
Please, be more specific. Are you talking about serverless functions? Which one?

**Comment by Zanz2** [comment]
If it is regarding the serverless functions then i was under the impression that you need nvidia container toolkit? (https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/#gpu-support)

**Comment by erenuito** [comment]
>

> Please, be more specific. Are you talking about serverless functions? Which one?

Yes it is severless functions.

**Comment by erenuito** [comment]
> If it is regarding the serverless functions then i was under the impression that you need nvidia container toolkit? (https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/#gpu-support)

I have already nvidia container toolkit.

**Comment by bsekachev** [comment]
Not all the serverless functions support GPU. Summary table might be found [here](https://github.com/opencv/cvat#deep-learning-serverless-functions-for-automatic-labeling). To deploy them on gpu, please use ``deploy_gpu.sh`` instead of ``deploy_cpu.sh``. 

Also read the [guide](https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/#gpu-support) you send to be sure you performed all the preparation steps.
