### ISSUE TITLE
Could I get the frame url when I just known the image id or image name?

### ISSUE THREAD

**Issue by FunnyDragonK** [opencv/cvat#6651]
I save the annotation info in "CVAT for images 1.1" format.

Then I want to get the frame url for a specific image to fix the wrong annotations, but there is only task_id and image_id saved for the image.

Is there a way to get the frame url from image_id or image name?

**Comment by bsekachev** [comment]
Knowing job_id, frame url is ``/tasks/<id>/jobs/<job_id>?frame=<image_id>``
Job id can not be provided in annotations, because literally the same frame can be in multiple jobs, for example with overlap. 

What is more, concept of CVAT jobs exist only inside the tool, annotation files don't know anything about them. 

But your point about quick searching for wrong annotation is valid, need to have a convenient way.

**Comment by FunnyDragonK** [comment]
Thanks for the rapid response! I don't know much about the details of the internal logic of CVAT. Just want to have this feature during the use of this wonderful platform. Looking forward to supporting the feature in the future.
