### ISSUE TITLE
How to set base path for reverse proxy?

### ISSUE THREAD

**Issue by kangsan0420** [opencv/cvat#6726]
I'd like to use nginx as a reverse proxy to access CVAT via the proxy (e.g., xxx.someurl.com/cvat). In other web frameworks, there's a configuration option called 'basepath' or 'baseurl' which prepends the default path to requested pages or resources (like favicons). How can I configure this in CVAT?

**Comment by azhavoro** [comment]
It is not supported natively by CVAT, but you can try to do so using nginx rewrite rules

**Comment by EugenDueck** [comment]
@azhavoro
The problem is that nginx won't be able to rewrite the absolute urls that cvat returns in e.g. html.
Example: `<script defer="defer" src="/assets/cvat-ui.425c874add07b9bfd832.min.js">`

If cvat is to support base paths - which would make it easier to integrate into a website without using e.g. sub-domains - there will need to be changes to the cvat source code.
