### ISSUE TITLE
some usage questions

### ISSUE THREAD

**Issue by lmessinger** [opencv/cvat#677]
Hi everyone

I have some questions regarding usage of this (amazing) system. Would appreciate any hint
1. what is the bug reporting system we can set when creating a task?
2. what is 'update task' that appears on the dashboard?
3. from looking at the API documentation (http://localhost:8080/api/swagger), i see various workflow related statuses.  /tasks/{id}/status - but it always returns 'finished'. is that a bug?

thanks very much
Lior

**Comment by bsekachev** [comment]
@lmessinger 
Hi, 
1. I suppose you tell about the "Bug Tracker" field. If you specify any link there, a created task will contain the button "Open Bug Tracker" which just open new tab with this URL. Usually we set there link to JIRA ticket where task is described. So, it's a link to any page with a detail description of a task. 
2. Update task allows you update labels and attributes for a task. You cannot delete old, but you can add new. 
3. There are many long processes on CVAT server (task creating, auto annotation, etc.). We can't perform them within one server request. For example for create task: we send one request to create new db model, we send one request to upload data to created model and then server starts to process them (it is long process), so, we just do these "check status" requests in order to know when process finish (dirty checks politics. Of course, it's more convenience to use websockets there, but django doesn't have native support for them). This time process is being done in background processes (rq workers).

I hope I answered your questions.

**Comment by lmessinger** [comment]
Great, thanks!

**Comment by bsekachev** [comment]
I'll close the issue. Don't be shy to ask your questions on [gitter](https://gitter.im/opencv-cvat):
