### ISSUE TITLE
Issue Converting CVAT COCO format for Instance Segmentation - "iscrowd" Parameter always 1

### ISSUE THREAD

**Issue by MercedesMarzoa** [opencv/cvat#7030]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I'm using CVAT to label data for instance segmentation. My intention is to use it with the YOLO version for instance segmentation. However, as this format is not available for download yet, so I am downloading the data in COCO format and then attempting to use `convert_coco` from https://docs.ultralytics.com/datasets/segment/.

I'm using the following code:

```python
from ultralytics.data.converter import convert_coco
convert_coco(labels_dir='path/to/coco/annotations/', use_segments=True)
```

However, this leaves the folder empty.

If I use this tool: https://github.com/ultralytics/JSON2YOLO, it also doesn't work because it requires the `iscrowd` parameter to be 0.

The problem is that when I download the dataset from CVAT, the `iscrowd` parameter is set to 1.
Why does this happen? I'm attaching an example image of the dataset and the downloaded file.
 Thank you very much.
![Screenshot from 2023-10-18 21-51-40](https://github.com/opencv/cvat/assets/117296706/76e483b8-2d58-472d-a8b1-12265e18d770)

[instances_default.json](https://github.com/opencv/cvat/files/13035337/instances_default.json)

**Comment by zhiltsov-max** [comment]
Hi! From the format [specification](https://cocodataset.org/#format-data):

> The segmentation format depends on whether the instance represents a single object (iscrowd=0 in which case polygons are used) or a collection of objects (iscrowd=1 in which case RLE is used).

CVAT follows this description, and produces 0 for annotations created as polygons, and 1 - for masks. That is, you can either annotate everything with polygons directly or convert your existing annotations to polygons. 

If you want to convert everything to polygons, you can do this using Datumaro (CVAT does this for several formats automatically, but not for COCO). Please note this conversion can introduce some artifacts in the annotations, most likely where there are "holes" in the masks, so it's recommended to check the result - you can import it in CVAT as well.

1. Export annotations from CVAT into the COCO format
2. Extract the downloaded archive
3. Run the following commands in the terminal:

```bash
# optional: create a separate virtual environment
python -m virtualenv venv
. venv/bin/activate

# install datumaro
pip install 'git+https://github.com/cvat-ai/datumaro@develop#egg=datumaro[default]'


# convert a .json file to polygons (is_crowd=0)
datum convert -o 'output-dir/' -f 'coco_instances' -i 'your.json' -if 'coco_instances'  -- --segmentation-mode polygons

# convert a .json file to masks (is_crowd=1)
datum convert -o 'output-dir/' -f 'coco_instances' -i 'your.json' -if 'coco_instances'  -- --segmentation-mode mask
```

Reference: 
- [`datum convert`](https://github.com/cvat-ai/datumaro/blob/v0.3/site/content/en/docs/user-manual/command-reference/convert.md)
- [COCO format options in Datumaro](https://github.com/cvat-ai/datumaro/blob/v0.3/site/content/en/docs/formats/coco.md#export-to-coco)

**Comment by zhiltsov-max** [comment]
@JNaranjo-Alcazar, this line can be executed in a terminal (aka command line), specific ways to reach it depend on the operating system you use - Windows, Linux, Mac OS, etc. Full descriptions for the command input parameters can be found, e.g. [here](https://openvinotoolkit.github.io/datumaro/latest/docs/command-reference/context_free/convert.html) and [here](https://openvinotoolkit.github.io/datumaro/latest/docs/data-formats/formats/coco.html#export-to-coco). Basically, we provide paths to the input and output dataset directories, and specify the COCO format.

**Comment by JNaranjo-Alcazar** [comment]
Thanks for the answer, by where I meant the path relative to the dataset.

Thanks again for que quick answer 😄

**Comment by JNaranjo-Alcazar** [comment]
hi again @zhiltsov-max !

I do not get what means input dataset path. So far, I have a json file with the annotations in iscrowd:1.

What do I have to pass as an input dataset?

Thanks!

**Comment by zhiltsov-max** [comment]
@JNaranjo-Alcazar, in this case you can specify the json file path directly, as you did. Please try to reinstall datumaro using this command: `pip install 'git+https://github.com/cvat-ai/datumaro@develop#egg=datumaro[default]'`. It seems in the newer version there is an error with the same input and output format.

**Comment by ryouchinsa** [comment]
Using the script [general_json2yolo.py](https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py), you can convert the RLE mask with holes to the YOLO segmentation format.

The RLE mask is converted to a parent polygon and a child polygon using `cv2.findContours()`.
The parent polygon points are sorted in clockwise order. 
The child polygon points are sorted in counterclockwise order.
Detect the nearest point in the parent polygon and in the child polygon.
Connect those 2 points with narrow 2 lines.
So that the polygon with a hole is saved in the YOLO segmentation format.

```
def is_clockwise(contour):
    value = 0
    num = len(contour)
    for i, point in enumerate(contour):
        p1 = contour[i]
        if i < num - 1:
            p2 = contour[i + 1]
        else:
            p2 = contour[0]
        value += (p2[0][0] - p1[0][0]) * (p2[0][1] + p1[0][1]);
    return value < 0

def get_merge_point_idx(contour1, contour2):
    idx1 = 0
    idx2 = 0
    distance_min = -1
    for i, p1 in enumerate(contour1):
        for j, p2 in enumerate(contour2):
            distance = pow(p2[0][0] - p1[0][0], 2) + pow(p2[0][1] - p1[0][1], 2);
            if distance_min < 0:
                distance_min = distance
                idx1 = i
                idx2 = j
            elif distance < distance_min:
                distance_min = distance
                idx1 = i
                idx2 = j
    return idx1, idx2

def merge_contours(contour1, contour2, idx1, idx2):
    contour = []
    for i in list(range(0, idx1 + 1)):
        contour.append(contour1[i])
    for i in list(range(idx2, len(contour2))):
        contour.append(contour2[i])
    for i in list(range(0, idx2 + 1)):
        contour.append(contour2[i])
    for i in list(range(idx1, len(contour1))):
        contour.append(contour1[i])
    contour = np.array(contour)
    return contour

def merge_with_parent(contour_parent, contour):
    if not is_clockwise(contour_parent):
        contour_parent = contour_parent[::-1]
    if is_clockwise(contour):
        contour = contour[::-1]
    idx1, idx2 = get_merge_point_idx(contour_parent, contour)
    return merge_contours(contour_parent, contour, idx1, idx2)

def mask2polygon(image):
    contours, hierarchies = cv2.findContours(image, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_TC89_KCOS)
    contours_approx = []
    polygons = []
    for contour in contours:
        epsilon = 0.001 * cv2.arcLength(contour, True)
        contour_approx = cv2.approxPolyDP(contour, epsilon, True)
        contours_approx.append(contour_approx)

    contours_parent = []
    for i, contour in enumerate(contours_approx):
        parent_idx = hierarchies[0][i][3]
        if parent_idx < 0 and len(contour) >= 3:
            contours_parent.append(contour)
        else:
            contours_parent.append([])

    for i, contour in enumerate(contours_approx):
        parent_idx = hierarchies[0][i][3]
        if parent_idx >= 0 and len(contour) >= 3:
            contour_parent = contours_parent[parent_idx]
            if len(contour_parent) == 0:
                continue
            contours_parent[parent_idx] = merge_with_parent(contour_parent, contour)

    contours_parent_tmp = []
    for contour in contours_parent:
        if len(contour) == 0:
            continue
        contours_parent_tmp.append(contour)

    polygons = []
    for contour in contours_parent_tmp:
        polygon = contour.flatten().tolist()
        polygons.append(polygon)
    return polygons 

def rle2polygon(segmentation):
    if isinstance(segmentation["counts"], list):
        segmentation = mask.frPyObjects(segmentation, *segmentation["size"])
    m = mask.decode(segmentation) 
    m[m > 0] = 255
    polygons = mask2polygon(m)
    return polygons
```

The RLE mask.

![スクリーンショット 2023-11-22 1 57 52](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/df2dfad5-a13f-49c6-818a-8aba1d3ce83c)

The converted YOLO segmentation format.

![スクリーンショット 2023-11-22 2 11 14](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/cc34027a-075f-4b67-8de7-bd2dddddac59)

To run the script, put the COCO JSON file coco_train.json into `datasets/coco/annotations`.
Run the script. `python general_json2yolo.py  `
The converted YOLO txt files are saved in `new_dir/labels/coco_train`.

![スクリーンショット 2023-11-23 16 39 21](https://github.com/ultralytics/JSON2YOLO/assets/1954306/c3d98120-66f5-4cb8-b74d-a500f0bd811d)

Edit use_segments and use_keypoints in the script.

```
if __name__ == '__main__':
    source = 'COCO'

    if source == 'COCO':
        convert_coco_json('../datasets/coco/annotations',  # directory with *.json
                          use_segments=True,
                          use_keypoints=False,
                          cls91to80=False)
```

To convert the COCO bbox format to YOLO bbox format.
```
use_segments=False,
use_keypoints=False,
```

To convert the COCO segmentation format to YOLO segmentation format.
```
use_segments=True,
use_keypoints=False,
```

To convert the COCO keypoints format to YOLO keypoints format.
```
use_segments=False,
use_keypoints=True,
```

This script originates from Ultralytics [JSON2YOLO](https://github.com/ultralytics/JSON2YOLO) repository.
We hope this script would help your business.

**Comment by vittorio-prodomo** [comment]
Hello. I understand that this is, for now, intended behavior, but it could cause problems down the line for frameworks that treat 'iscrowd=1' annotations differently. Also, I would like to point out (as already said earlier by @zhiltsov-max) that CVAT already successfully implements mask-to-polygon conversions for different export choices. For example, when converting to YOLO Ultralytics segmentation, all the donut shapes created with the brush tool as masks in cvat are correctly converted to closed polygons, with the trick explained above. So if this problem has been already solved and is somewhere in the codebase, why isn't this used also in the COCO export choice?

**Comment by zhiltsov-max** [comment]
@vittorio-prodomo, could you please describe the desired behavior more specifically? This issue has been discussed for quite some time already, and several conversion scripts were [provided](https://github.com/cvat-ai/cvat/issues/7030#issuecomment-1770555050) - both from masks to polygons and vice versa. COCO supports both masks and polygons, so CVAT exports them as they are, without extra conversions that are required by other formats that support only one option. If you see an error in CVAT implementation or a way to improve the current behavior, please let us know.

**Comment by vittorio-prodomo** [comment]
Yes of course, let me explain a bit more in detail @zhiltsov-max .
You are theoretically right to say "well, COCO supports both masks and polygons, so I can let CVAT export brush masks to masks and polygons to polygons...". But now that I delved deep enough into the field of object detection and instance segmentation (and the COCO and the YOLO Ultralytics formats), I think that the reality is a bit different. In the comment you linked, you also provided a link to the official specifications of the COCO format ([here](https://cocodataset.org/#format-data)). And well, if we actually take that specification literally, it says:

> The segmentation format depends on whether the instance represents a single object (iscrowd=0 in which case polygons are used) or a collection of objects (iscrowd=1 in which case RLE is used)

So it's pretty clear that the usual intended behavior of COCO annotations is that the following should always be true:
Mask annotation in RLE <---> iscrowd=1
Polygon annotation       <---> iscrowd=0

To be clear, collections of objects are like those areas of our image where we now everything belongs to the same class, but it's very difficult or outright impossible to perfectly separate each instance. Think about a massive crowd of people seen from afar, or think about trees very close to each other with the branches intertwining. The iscrowd was born to just signal difficult labels that are treated entirely different in the downstream ML training pipelines, or sometimes outright ignored/skipped.

I then tried to actually look into **what would happen** in some famous, COCO-based training frameworks (e.g., Detectron2, MMDetection) if we had some annotations that don't follow this pattern, but that are, for example, RLE masks with iscrowd=0 (because maybe what we labeled in CVAT with a mask was not, in our mind, a "collection of objects" but still one single object, and we just used the brush tool because it was more convenient, or it was an occluded object that could only be labeled with that and not with polygons). I know currently CVAT puts iscrowd always to 1 (see [here](https://github.com/cvat-ai/cvat/issues/7030#issuecomment-1770555050)), but let's suppose we manually changed that to 0.

And apparently, those algorithms indeed **support** RLE masks with iscrowd=0. Which is not surprising since, no matter the input format, somewhere along the pipeline these annotations are all converted into binary masks to be actually used during training. So some algorithms are smart enough to only look at the iscrowd attribute to decide wheter to skip/ignore that sample. But not **all** algorithms available around us are **that smart** (see the rest of the explanation below).

So basically we have 2 separate problems right now, in my opinion, in how CVAT currently behaves:

Problem 1) Even though we accepted to just feed our models with RLE masks even when those masks don't represent "collections of objects", we still have the problem that CVAT **indiscriminately** puts iscrowd equal to 1 for **all** the masks annotations, regardless of the semantic meaning behind it and the consequences for how other, downstream scripts expect the data.

Problem 2) Even though famous training algorithms still "work as intended" with RLE masks that have iscrowd=0, there is still a huge amount of code around us (plenty of format conversion scripts, like [this](https://github.com/ultralytics/JSON2YOLO) for example) that **expects** our COCO annotations to follow that strict pattern I said at the beginning and that is reported in the COCO official specs: RLE masks have always iscrowd=1 and polygon-based masks have always iscrowd=0. This means that if, somewhere along our pipeline, we give our CVAT-generated COCO labels to one of these scripts, they probably will completely ignore all the masks that we created in CVAT with the brush tool.

Let me reiterate more clearly what is actually a typical, practical problem I face in a CVAT labeling workflow:
- I found myself in need to label a single object (let's say, a car) that is partially occluded by something. But the occlusion is done in such a way (think about a street light pole) that, in order to "cover" my car pixels and not the pole pixels, I would need two, disjoint polygons or masks.
- CVAT doesn't allow me to draw multiple polygons and associate them to the same object instance.
- So I have no choice but to use masks with the brush tool, but this brings us Problems 1 and 2 explained before.
- So now, after exporting, I have to:
    - either accept to work with RLE annotations that "kinda" break the COCO protocol, so I simply run a "find and replace" to put all the iscrowd parameters equal to 0 (assuming I had no examples in my dataset that actually required the iscrowd attribute in the first place). 
    - or I need to come up with my own conversion script that via contouring operations extracts multiple polygons from my RLE masks and puts them in the "list of lists" format, the COCO typical format for polygons coordinates.

So to wrap up, there are different steps, some smaller and other bigger, that could be taken in the future to "lessen the burden" on the CVAT user. Because in my ideal scenario (and I guess this goes for lots of people), I would like to have to perform as few intermediate pre-processing steps as possible, in between the "CVAT export" phase and the actual model training.

Potential fixes could be (from the simplest to the more complex ones):
- Quick fix to Problem 1: stop indiscriminately putting iscrowd equal to 1 for all the masks created with the brush tool. Yes I know that from the user perspective this is quickly solved with a trivial "find and replace", but still.
- Long-term fix to Problem 1: in order to actually support the semantic meaning behind the 'iscrowd' parameter, we could think for example to include an actual 'iscrowd' attribute in our annotations. This could either be an ever-present attribute (like the 'occluded' property) or an attribute that every user needs to include in their CVAT task by themselves. Then, when exporting to COCO format, CVAT just needs to check that attribute to understand what value to give to the COCO iscrowd.
- Ideal fix to Problem 2: since CVAT is already using, behind the curtains, smart conversion scripts (that work pretty well also with masks with holes, I tested it when exporting donut-shaped masks to YOLO Ultralytics format), the fix here would simply be to use the same scripts also for the COCO export. Maybe we could imagine to leave the choice to the user, afterall. Like a toggle (like the ones we already see in other places of CVAT) that says "convert masks to polygons". Coupled with this, I would also include a another toggle to decide whether the conversion process should ignore masks with the iscrowd CVAT attribute (from the previous proposed fix) equal to 1, and leave them in RLE format. Of course, to literally follow the COCO standard, both the toggles should be left set to True, but that's up to the user.
- More complex, additional/orthogonal feature to tackle Problem 2: to avoid even the slightest loss in annotation accuracy (due to polygons approximations after contouring), we could also think, at some point in the future, to actually allow the polygon tool in CVAT to draw different, disjoint polygons that **belong to the same object**. This would perfectly translate into COCO because COCO supports lists of polygons coordinates. Then of course, when exporting to formats that strictly follow the rule "one object, one polygon" (like YOLO Ultralytics), these polygons would have to be broken down to different instances (something that, by the way, already perfectly happens when converting disjoint masks of the same object to YOLO Ultralytics format).

Sorry for the long explanation, but I hope everything is clear now.

**Comment by zhiltsov-max** [comment]
@vittorio-prodomo, thank you for the expanded answer and the information provided. I'd like to add several comments about the points mentioned. CVAT can certainly be improved, but some of the ideas are already implemented.

> I found myself in need to label a single object (let's say, a car) that is partially occluded by something. But the occlusion is done in such a way (think about a street light pole) that, in order to "cover" my car pixels and not the pole pixels, I would need two, disjoint polygons or masks.
> CVAT doesn't allow me to draw multiple polygons and associate them to the same object instance.

> More complex, additional/orthogonal feature to tackle Problem 2: to avoid even the slightest loss in annotation accuracy (due to polygons approximations after contouring), we could also think, at some point in the future, to actually allow the polygon tool in CVAT to draw different, disjoint polygons that belong to the same object. This would perfectly translate into COCO because COCO supports lists of polygons coordinates. Then of course, when exporting to formats that strictly follow the rule "one object, one polygon" (like YOLO Ultralytics), these polygons would have to be broken down to different instances (something that, by the way, already perfectly happens when converting disjoint masks of the same object to YOLO Ultralytics format).

It is possible to join several polygons into a group. In this case, they will be exported as a single annotation with multiple polygons (the COCO format supports this option as well, exactly for this use case). The other parameters, such as label and attributes, will be taken from the largest, by area, polygon in the group. Annotations can be grouped by using the "Group shapes" (default keybind G) in the editor.

<img width="340" height="57" alt="Image" src="https://github.com/user-attachments/assets/5136763b-9b8d-4f78-9338-d4ef09323f86" />

Current groups can be visualized using this button:

<img width="500" height="392" alt="Image" src="https://github.com/user-attachments/assets/5f3e0701-6339-450e-b3ce-91fe8e2b1dab" />

Mixed mask/polygon groups will be merged into a mask, then exported according to the general rule.

> Long-term fix to Problem 1: in order to actually support the semantic meaning behind the 'iscrowd' parameter, we could think for example to include an actual 'iscrowd' attribute in our annotations. This could either be an ever-present attribute (like the 'occluded' property) or an attribute that every user needs to include in their CVAT task by themselves. Then, when exporting to COCO format, CVAT just needs to check that attribute to understand what value to give to the COCO iscrowd.

For some formats, CVAT supports format-specific attributes, if they are defined in the task labels. Speaking about COCO, the `iscrowd` attribute is supported, but not exactly as you described. If the `is_crowd` (checkbox) attribute is defined for the label, it allows to control how each polygon and/or mask group (an _instance_) is exported, performing conversions if needed. I agree that this is only a partial solution, because it won't allow you to export a mask with `iscrowd=0` or a polygon with `iscrowd=1`. The reasons for this are mostly historic, because this parameter was used before the brush tool was added into CVAT to convert into the desired annotation type on export. 

The documentation about format support is available [here](https://docs.cvat.ai/docs/manual/advanced/formats/format-coco/#coco-export), these features are mentioned in the Export section.

> Ideal fix to Problem 2: since CVAT is already using, behind the curtains, smart conversion scripts (that work pretty well also with masks with holes, I tested it when exporting donut-shaped masks to YOLO Ultralytics format), the fix here would simply be to use the same scripts also for the COCO export. Maybe we could imagine to leave the choice to the user, afterall. Like a toggle (like the ones we already see in other places of CVAT) that says "convert masks to polygons".

We discussed such a toggle at some point, it's currently considered a part of the issue https://github.com/cvat-ai/cvat/issues/1804. So far, the online platform has a [paid feature](https://docs.cvat.ai/docs/enterprise/shapes-converter/) for batch annotation type conversion in the editor.

**Comment by vittorio-prodomo** [comment]
Thank you for your detailed answer as well!
I was not aware that the "groups" in CVAT actually translated into polygons belonging to the same instance, in the exported COCO annotations! Thank you for clarifying that! And is it correct to assume that the groups are instead ignored when exporting, for example, to YOLO Ultralytics format for Segmentation?

About the iscrowd attribute, I also was not aware that, if we define it in our CVAT Job, it gets picked up and correctly used during the export process! Again, thanks for the patience in clarifying that! But I have a doubt. You said that based on the iscrowd value CVAT will perform "conversions if needed", but you also say later that we can't export a mask with iscrowd=0 or a polygon with iscrowd=1. Can you clarify for me what actually happens in the following scenarios?

- I have some polygons under the same group. All of them have iscrowd=0.
- I have some masks under the same group. All of them have iscrowd=0.
- I have a mixed group of polygons and masks, all with iscrowd=0.

What should I expect to see in the exported COCO annotations, for each of these cases? I know the first case is trivial and it requires no conversions at all, but I just included it for completeness.

**Comment by zhiltsov-max** [comment]
> And is it correct to assume that the groups are instead ignored when exporting, for example, to YOLO Ultralytics format for Segmentation?

Yes, this group export logic is not currently applied for YOLO segmentation export, as the format supports only 1 polygon per annotation. The groups are not being merged automatically now. It's being supported in all the other mask formats though, so maybe it should be considered a bug.

> Can you clarify for me what actually happens in the following scenarios?

The general algorithm [is the following](https://github.com/cvat-ai/datumaro/blob/26d5f3508e80e40d81034b8c504e4790bdc74b65/src/datumaro/plugins/data_formats/coco/exporter.py#L344):
1. Find the largest annotation in the group (the group "leader").
2. If `is_crowd` is specified in the leader, use this value. If `is_crowd` is not specified in the leader, try to infer this value according to the common annotation type in the group.
3. Determine the group shape. If there are masks in the group, merge them into a single mask. 
4. Save the shape corresponding to the determined `is_crowd` value. Convert masks into polygons or vice versa, if needed. Note that a single mask with multiple disjoint components will be splitted into several polygons during the conversion. 
5. Save other instance properties (label, attributes) based on the leader annotation.

> I have some polygons under the same group. All of them have iscrowd=0.

Will export as polygons, iscrowd=0.

> I have some masks under the same group. All of them have iscrowd=0.

Will merge masks into one, convert to a polygon, export as polygon(s), iscrowd=0.

> I have a mixed group of polygons and masks, all with iscrowd=0.

Will merge masks into one, convert it to polygon(s), append other polygons. Export as polygons, iscrowd=0.

**Comment by Abdul-Mukit** [comment]
@zhiltsov-max 
These decisions are really problematic.  
The user decides that the brush tool/mask is the best choice for a certain object. And knows they are is_crowd=False (individual instances). During export, Datumaro and CVAT decide not to respect the users' choices and convert everything to polygons. During the process, in many samples, datumaro fills holes that the user had carefully created in masks. 

This makes the usage of CVAT harder for the user. I have objects that have 10 different holes. Creating masks with holes, using SAM, was just a one-click job. But CVAT won't allow me to export them as is_crowd=False. They are automatically converted to is_crowd=True! In order to create holes in annotations and be able to export them as is_crowd=False, I now have to very carefully maneuver and draw very difficult polygons.

Please at least give the users some options during export. They should be able to choose whether CVAT should respect the users' choices of shapes and the is_crowd value.

**Comment by zhiltsov-max** [comment]
@Abdul-Mukit, 

> The user decides that the brush tool/mask is the best choice for a certain object. And knows they are is_crowd=False (individual instances). During export, Datumaro and CVAT decide not to respect the users' choices and convert everything to polygons. During the process, in many samples, datumaro fills holes that the user had carefully created in masks.

Could you provide an example of this behavior and the CVAT version? Maybe a video or a task backup. I'm not sure why such a type conversion could happen. And if it happens, Datumaro should already be clever enough to cut holes in polygons.

Thank you for mentioning the SAM example, however. There is a shape mode toggle in the tool selection and also a mask to polygon conversion function in the UI. However, I can see that this conversion does fill the holes indeed. It looks like a UI problem, @bsekachev.

<details>

https://github.com/user-attachments/assets/74eed7b0-16ea-4f63-b7a1-2f79ec3c8a39

</details>

**Comment by Abdul-Mukit** [comment]
@zhiltsov-max thank you for your quick response. 
I used the datumaro (1.12.0) programatically. Code looks something like this:  
```
output_dataset = Dataset.from_extractors(*datasets)  # all coco formatted, from CVAT

if force_set_is_crowd_to_flase:
    for dataset_item in output_dataset:
        for annotation_shape in dataset_item.annotations:
            if "is_crowd" not in annotation_shape.attributes:
                continue
            annotation_shape.attributes["is_crowd"] = False

# do some resizing and splitting transforms on output_datasets

output_dataset.export(
    save_dir=output_dataset_path,
    format=output_dataset_format,  # coco
    save_media=True,
    reindex=True,
    progress_reporter=SimpleProgressReporter()
)
```

All `datasets` are exported from the same project in CVAT. (I didn't have the iscrowd attribute defined in CVAT project settings. Not sure if that matters). One dataset is only based on RLE-masks. The others are only polygon-based. After exporting `output_dataset`, when I load back to CVAT, I see that all RLE masks have been converted to polygons with the holes all filled.
I understand that `iscrowd=False` is not compatible with masks according to datumaro. This is aligned with docs about `is_crowd` for CVAT: https://docs.cvat.ai/docs/dataset_management/formats/format-coco/#coco-export

The expected behavior in this case for me was that the datumaro won't do the RLE -> polygon conversion automatically. Instead should allow for exporting RLE masks with iscrowd=False.  

I can try to set an attribute called `is_crowd` in project settings and see if I can export RLE masks with is_crowd=False.  
CVAT Server version: 2.44.2
CVAT UI version: 2.44.2

**Comment by Abdul-Mukit** [comment]
@zhiltsov-max, thank you. 
After adding the `is_crowd` attribute to CVAT project settings, it sort of worked out. There was still the unintended change from RLE-mask to polygon. But the holes were preserved. I added screenshots and the dataset of the dummy project. 

For production, I think it will be better if this unintended change can be avoided. Annotators might spend a lot of hours visually making sure all the RLE-masks are correct. They export the dataset, and ML engineers start training with the exported dataset. There is no one in the middle to verify whether `datumaro` hadn't made any mistakes in preserving the holes. There is this blind spot. 

What I am trying to say is we should be able to export what we have visually signed off on. During exporting, the dataset shouldn't just change into anything we haven't signed off on.  


### Project:  
<img width="1026" height="1113" alt="Image" src="https://github.com/user-attachments/assets/c22db707-fd3a-44ca-9836-380e05f1db84" />  

### Initial annotation using RLE-masks:
<img width="1279" height="1255" alt="Image" src="https://github.com/user-attachments/assets/02d66057-904c-4666-a9fe-350a4aef69e2" />  

### Export to COCO Format:
<img width="1009" height="470" alt="Image" src="https://github.com/user-attachments/assets/f531f9d6-dc92-491b-a1ad-d5ff1e954afb" />  

I checked the exported `instances_default.json` file manually. Masks were already converted to polygons.  

### Load back the exported dataset:
I made sure not to check the "convert masks to polygon" option during import.  

<img width="1274" height="1196" alt="Image" src="https://github.com/user-attachments/assets/62a238fc-6dec-470c-90c8-2dbac76d2267" />  

[button_single_image_dataset_exported.zip](https://github.com/user-attachments/files/24130518/button_single_image_dataset_exported.zip)

**Comment by zhiltsov-max** [comment]
@Abdul-Mukit, @vittorio-prodomo 

Assuming that the training framework deviates from the format specification, so far I can suggest the following.

If you want to annotate as it is more convenient at the moment and also want to control the attribute on per object basis directly:

Create a custom checkbox attribute called a little bit differently (e.g. `is-crowd` or `iscrowd`) and annotate it in each instance manually. Then use a simple script to move the attribute to the COCO default location:

```python
import json
import sys
from pathlib import Path

filename = Path(sys.argv[1])

with filename.open() as f:
    data = json.load(f)

# move the custom "myiscrowd" attribute into the standard COCO "iscrowd" location
for annotation in data["annotations"]:
    annotation["iscrowd"] = int(annotation["attributes"].pop("myiscrowd"))

with filename.with_stem(filename.stem + "-converted").open("w") as f:
    json.dump(data, f)
```

Call it like this: 
```
python ./convert_coco_iscrowd.py \
  "job_12345_annotations_coco 1.0/annotations/instances_default.json"
```


If you also want to enforce a specific conversion (e.g. always masks or polygons), it can be done using [Datumaro CLI](https://open-edge-platform.github.io/datumaro/stable/docs/data-formats/formats/coco.html#export-to-coco):

```
datum convert \
  -if "coco_instances" \
  -i "job_12345_annotations_coco 1.0/annotations/instances_default.json" \
  -f "coco_instances" \
  -o "job_12345_annotations_coco 1.0-polygons" \
  -- --segmentation-mode "polygons"
```

or the API parameter:

```python
import datumaro as dm
dataset = dm.Dataset.import_from("instances.json", "coco_instances")
dataset.export(..., segmentation_mode="polygons")
```

Please note that the conversion into polygons with holes is only supported in our fork of Datumaro and not in the upstream version. Our fork is available here: https://github.com/cvat-ai/datumaro.
