### ISSUE TITLE
Error when downloading mask

### ISSUE THREAD

**Issue by 4sfaloth** [opencv/cvat#749]
Hi,

I am experiencing an issue when trying to download mask annotations for a dataset. I can correctly visualize the annotations on cvat, and I can also download the annotations as .xml but if i request the mask .png I get this error:
`Exception at line 307: input type not supported`

CVAT logs show the same thing. Any idea what may be happening?

thanks in advance

**Comment by azhavoro** [comment]
Hi, @4sfaloth 
Could you please attach your annotation in xml format?

**Comment by 4sfaloth** [comment]
@azhavoro thanks for following up and I am sorry for taking so long to respond, but I've been out and with no access to the server machine for the last week.

Here you go (had to zip it for some reason):
[CvatMaskProblem.zip](https://github.com/opencv/cvat/files/3727820/CvatMaskProblem.zip)

I had to manually edit the task name and the image names for privacy concerns, but I believe that is not relevant for the case.
Thanks again for following up on this

**Comment by zhiltsov-max** [comment]
I suppose it has been solved somewhere in between, or should be solved by #1352. Feel free to reopen.

**Comment by zhiltsov-max** [comment]
The problem should have been here: https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/_mask.pyx#L307
as the old mask export implementation used pycocotools to convert polygons to masks. 

It has been fixed by changing the implementation to use Datumaro and then by disallowing truncated polygons with < 3 points in https://github.com/opencv/cvat/pull/975.
