### ISSUE TITLE
Do you know about CVAT design flaws?

### ISSUE THREAD

**Issue by AndreyTulyakov** [opencv/cvat#7561]
**Dear CVAT Development Team.**

I hope this message finds you well. My team and I are currently considering the integration of the CVAT (markup, datasets management) with our CV-services.

We would like to inquire about your opinion, specifically about architectural, integration or data model design flaw within CVAT that could pose as explicit or frustrating limitations.

Please share your opinion on what you would like to change if you had the opportunity to start development over.

_We understand that no tool is without its challenges, and we believe that having a comprehensive understanding, including the known limitations, will help us better prepare for integration and future use._

Thank you for your time and consideration.

**Comment by nmanovic** [comment]
@AndreyTulyakov, it seems that your question is too broad to provide a specific answer. CVAT has many open-sourced features available for you to review and experiment with, but in order to assist you better, we need to know more about your intended usage and integration plans. Please provide us with more specific details so that we can help you in a more accurate way. Additionally, if you require further assistance, our team offers consulting and enterprise support. You can follow that path if you need help with integration from our core team. I hope this information helps, and please feel free to ask any further questions you may have. I will now close this issue.
