### ISSUE TITLE
Job stage vs status

### ISSUE THREAD

**Issue by bedilbek** [opencv/cvat#7566]
What is the difference between job status and stage? Why there can't be only one of them?
@bsekachev @nmanovic

**Comment by adkbbx** [comment]
@bedilbek 
From what I can understand 

1. Job Status: Indicates the overall condition of a job (new, in progress, rejected, completed).
2. Stage: Represents the specific phase within the job's workflow (annotation, validation, acceptance).

Both provide different perspectives on the job's progress.

For more details, you can even refer to the CVAT documentation as well: 
1. [Jobs](https://opencv.github.io/cvat/docs/manual/basics/task-details/#:~:text=task%20is%20created.-,Jobs,-%E2%80%94%20is%20a%20list)
2. [Vocabulary](https://opencv.github.io/cvat/docs/manual/basics/vocabulary/#state:~:text=3D%20Object%20annotation-,State,-State%20of%20the)

Hope this helps!

**Comment by bedilbek** [comment]
@adkbbx 
Actually when I posted my question I had already read every related information in the docs and could not find it, so I posted. Also, I guess you didn't read my question carefully, I didn't ask what is Job state and what is Job stage, because I already read about them, and there are documented information about them:


![image](https://github.com/opencv/cvat/assets/23011104/1cd9f2bb-f606-4608-8f4c-01c8003778f1)


![image](https://github.com/opencv/cvat/assets/23011104/1dc4f3a8-444d-423a-96dc-e2dbd056040b)

I asked the different question which was related to difference between Job status and Job stage. Because there is no information about Job status in the documentation. So please if you don't read carefully or do not understand question enough, do not try to answer it

**Comment by adkbbx** [comment]
@bedilbek 
I apologize if I sounded rude in my previous message and I understand I may have been hasty in responding without fully understanding your question because I was eager to help.  I'll make sure to take more time to understand queries before replying in the future. 
I also acknowledge the gap in our documentation regarding the distinction between Job status and Job stage. Thank you for pointing it out. I hope the core team can provide better assistance with your query. Have a great day!

**Comment by bsekachev** [comment]
Hello, job `status` is legacy field for backward compatibility. Once, we will remove it.
