### ISSUE TITLE
Add Annotation-instance-wise mask in `Dump Annotation`

### ISSUE THREAD

**Issue by rsnk96** [opencv/cvat#771]
Currently, the `MASK ZIP 1.0` groups all annotations of the same label type into the same colour. It would be nice to be able to generate segmentation maps from the drawn labels where each annotation (i.e. each `Object` in the Right hand side panel in the labelling UI) would come in a different colour.

This feature would be useful for the following use cases
* Instance/Panoptic Segmentation
* When one would like to distinguish the same label, but with different attributes

**Comment by Zahid-QT** [comment]
Hi , Is there any update on the issue?

**Comment by nmanovic** [comment]
@rsnk96 , @zhiltsov-max , I believe the issue was fixed. Now you can download segmentation and instance segmentation at the same time. I will close the issue. Don't hesitate to reopen it if you think that the current solution doesn't work for you.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/40690625/77225707-9badca80-6b82-11ea-8c92-f696cf08107e.png">
