### ISSUE TITLE
Slice/join objects on the same frame

### ISSUE THREAD

**Issue by rsnk96** [opencv/cvat#774]
Features that would help improve productivity:
* Subtract shapes within frame
* Merge shapes within the same frame
* Split shape into multiple shapes within the same frame https://github.com/opencv/cvat/issues/690

Possible issues to consider when doing this:
* Which attributes of the  two shapes to maintain, how to handle conflicting attributes

**Comment by nikste** [comment]
+1

**Comment by RGring** [comment]
+1

**Comment by veer5551** [comment]
Hello,
Any updates on this?

Thank!

**Comment by amburkoff** [comment]
We also need such a tool!
Sometimes it is necessary to cut from one polygon to another in order to remove some details from the surface. The CVAT does not currently have a polygon subtraction operation. An example of how this is done in supervise.ly is shown in the video. It also shows how you have to remove unnecessary parts in CVAT (not convenient).
[video](https://drive.google.com/file/d/1cZZNKtQiYo2svJlVaUOHy2U3WM_OfNb1/view?usp=sharing)
