### ISSUE TITLE
Left/Right arrow move cursor in text input

### ISSUE THREAD

**Issue by saj940826** [opencv/cvat#776]
Hi, all
currently, I upload the cvat and found that the left/right arrow event is replaced by move filtered frame. I also try modify cvat/apps/engine/static/engine/js/userConfig.js file to use Shift + left/right arrow for move frame but it doesnt work. In previouse version, when focus on  text input, arrow event works fine but now I think moving frame event is a global event and  overwriting the input event.
Any suggestions?

**Comment by nmanovic** [comment]
@saj940826 , I'm not sure that I understand the problem. Could you please provide an exact scenario which doesn't work for you?

**Comment by nmanovic** [comment]
@saj940826 , need your answer to understand the problem deeper. For now I don't see any reply already a month. I will close the issue. Please don't hesitate to reopen it if you have more information for us.

**Comment by archwolf118** [comment]
@nmanovic When I input the "text attribute" under some label, if I press "left arrow" or "right arrow" for changing some text in some place, but the page will move to the next or previous pic.  that is not convenient, I suggest  cancel the right arrow and left arrow, because we already have the D and F shorcut. Thank you!
