### ISSUE TITLE
New User Questions 

### ISSUE THREAD

**Issue by endo123** [opencv/cvat#84]
I am evaluating this for our project and had a few questions:

1. What does tf_annotation app do? Even without installing and activating it (since my machine didn't have a GPU), I am able to create shapes in both annotation and interpolation mode, so not sure.

2.  Where are the extracted files from the video saved and what is their format? 

3. Is there a limit on the video size that can be processed within a single task? It does complain when I try to use larger videos, but not sure of the file size limit

Thanks!

**Comment by nmanovic** [comment]
Hi,

You can use our [gitter](https://gitter.im/opencv-cvat) for such questions.

1. tf_annotation is used for auto annotation. You will have one more button for each task in dashboard. If you push the button it will annotate the selected task in background. For example, let you have a task with "person" label. Such label is supported for auto annotation. Thus after you push "TF annotation" button all person will be annotated by TensorFlow OD API automatically. You will need just verify and fix missing annotations or update incorrect one.

2. Each video is split by ffmpeg on frames in jpg format. You can specify quality of such jpg when you сreate a task. Such frames are located inside /home/django/data/``<task_id>``/ directory inside your container. The directory corresponds to cvat_data volume which can be bind with a host directory.

3. There are two options to upload data: from local host and from a ``share`` directory. You cannot upload to much data from a local host just because it will be too long. For huge tasks it is better to use ``share`` option. Please read [documentation](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/user_guide.md) for more details.

Does it answer your questions?

**Comment by endo123** [comment]
Yes, it does! Thanks for your prompt response.  For our project, the TF annotation will not help as the data set is quite different. So glad to know that a GPU based server is not mandatory for our use. I will look into using gitter for other questions.
