### ISSUE TITLE
Tfrecord Dump Error

### ISSUE THREAD

**Issue by san999p** [opencv/cvat#866]
If you dump annotation for `TFRecord Zip 1.0` then there will be a lot of problem with the dumped file.  (`/annotation/tfrecord.py`)

1) First problem is with `label_map.pbtxt`. The problem is `id = 0` is reserved for background. So, it needs to start from 1 NOT 0. This can easily be fixed.

2) Tfrecord contains encoded images so that training can be faster. But if you look at the current file, it does not encode images into tfrecord. If you use this tfrecord in TF Detection API, it will throw an error.

**Comment by nmanovic** [comment]
@san999p ,

Thanks for the report. The second problem will be fixed in our new dataset framework (datumaro). Dump annotations is used only to dump annotations (without images). We recently introduced `export as dataset` feature. Now it doesn't support TFRecord format but it will do. The feature will export images + annotations. Please stay tuned.

**Comment by zhiltsov-max** [comment]
@san999p, please check if [this](#894) PR satisfies your needs - you can test it by exporting a dataset.
